### ISSUE TITLE
Adaptar el estilo del site existente

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#1]
El .NET Framework genera el template predeterminado de estilos usando [Twitter Bootstrap](www.getbootstrap.com)

De esta tarea se desprenderán tareas más pequeñas para emular el diseño actual de emplea.do

**Comment by RaulMonteroC** [comment]
Entiendo que esto debe estar cerrado porque se ha ido trabajando en los issues #61 , #62 , #68
