### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#100]
- Poder ver los detalles del perfil del usuario logeado
- Agregar una imagen al perfil donde se podra almacenar el logo de la empresa

**Comment by luis-ramirez** [comment]
que opinan de esto?

**Comment by RaulMonteroC** [comment]
Según entiendo eso se ha quedado para la segunda etapa. Actualmente creo que faltan dos items de la etapa 1 por agotar antes de trabajar ahí. Dicho eso, considero que es buena idea.

**Comment by RaulMonteroC** [comment]
El user profile en este caso se refiere a la empresa o al candidato ?

**Comment by anyeloamt** [comment]
Como ya tenemos un user profile que se refiere a la empresa (PR #301), creo que ya podemos desarrollar este issue.
Tendríamos que:

* Mover los fields de información de la empresa del `JobOpportunity` al `UserProfile` (podríamos cambiar el nombre de UserProfile a uno más adecuado para la empresa o dejarlo así y guardar la información en otra entidad que se relacione con UserProfile)
* Desarrollar una sección de "personalizar" para que el usuario pueda registrar el nombre, logo, email y URL de la empresa.

**Comment by claudiosanchez** [comment]
Los campos relacionados a una empresa deben de ir en una entidad para ese fin; no en UserProfile directamente.

**Comment by anyeloamt** [comment]
Bien, entonces tendremos que hacer algo con UserProfile, actualmente está siendo utilizado como una empresa per se, podríamos crear una entidad para la empresa y referenciar a UserProfile, pero creo que estaríamos redundando un poco si UserProfile sólo se va a utilizar para empresas.

Si utilizamos UserProfile tanto para empresas como para candidatos (supongo que se implementará en un futuro no muy lejano) la información no sería redundante pero sí más compleja. Tendríamos u n UserProfile que sería tanto para empresas como para candidatos y habría que utilizar algún mecanismo para diferenciarlos (UserType o algo así).

¿Cuál creen que sería la mejor manera de implementarlo?

**Comment by RaulMonteroC** [comment]
@anyeloamt Precisamente. Lo más probable es que en algún momento tengamos login para candidatos tambien. Para hacer una solución que soporte esto (y abundar un poco más a tu propuesta), se me ocurre lo siguiente:

- Crear un tipo de usuario (compañia y candidato) y hacer que la entidad usuario le haga referencia.
- Crear una entidad compañia 
- La entidad compañia tendria una referencia al usuario (foreigh key)

Esto permite que la entidad usuario permanezca limpia, solo con la información necesaria para iniciar sesión y por tanto cuando se necesite crear la parte del candidato sería simplemente crear una entidad nueva y hacer referencia al usuario.

**Comment by RaulMonteroC** [comment]
Adicionalmente, para este issue podemos simplemente utilizar los campos de la empresa como los que aparecen y son modificables desde el perfil del usuario que tenemos hoy día. La información que se tenga de aquí es la que se utilizara para llenar automáticamente los campos relacionados en el formulario de creación de empleo (nombre de la empresa, url, logo, etc)

**Comment by anyeloamt** [comment]
@RaulMonteroC Me parece bien, puedo tomar este issue.

**Comment by RaulMonteroC** [comment]
Posibilidad de colocar mas detalles acerca de la empresa que ofrece el puesto

- Redes Sociales (FB, Twitter,Etc)
- Descripcion sobre la empresa
- Un video si lo posee
- Direccion
- Telefono

Esta información es del issue #156 (hecho por @luis-ramirez)  que fue cerrado para incluirse dentro de este por ir de la mano. 

Por favor incluye estos campos tambien.

**Comment by anyeloamt** [comment]
@RaulMonteroC Ok
