### ISSUE TITLE
Use a separate connection file

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#111]
Because i want to be able to use my outdated sql server 2008 R2, and because someone may want to use their own custom connection string, doing it this way there would be less risks of getting some conflicts. Also, security and stuff

**Comment by luis-ramirez** [comment]
Puedes hacer un fork y crear una exclusion en tu .gitignore para que no suba el web.config, btw, si tienes instalada VS2015 e instalaste la version express de sql server no tienes que hacer eso, porque se llama igual

**Comment by eatskolnikov** [comment]
@luis-ramirez esto no toma mucho y sirve también para poder usar un .mdf en vez de tener el servidor de la base de datos arriba consumiendo memoria :v

**Comment by claudiosanchez** [comment]
@eatskolnikov Vamos por parte. Como que use a separate 'connection file'?  El conectionstring se configura por default en el web.config; y si tu quieres usar un DB diferente (i.e.: un archivo mdf) lo puedes hacer, sin tener que alterar el codebase.

**Comment by eatskolnikov** [comment]
@claudiosanchez es que si cada quien tiene una base de datos en un sitio diferente o como en mi caso quiere usar una base de datos en un archivo hay que cambiar el webconfig y después deshacerlo cuando se haga commit. Eso da a conflict en cualquier momento.
Para hacer lo que pido nomas hay que poner esto en el web.config:
```xml
    <connectionStrings configSource="connections.config"></connectionStrings>
```
y agregar el archivo connections.config con el connection string, en mi caso:
```xml
    <connectionStrings>
    <add name="EmpleoDotNetConn" connectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\Empleodotnet.mdf;Initial Catalog=Empleodotnet;Integrated Security=True" providerName="System.Data.SqlClient" />
    </connectionStrings>
```
No hay ni que incluirlo en el proyecto, con que este en el mismo folder que el web.config es suficiente.

PS: No quiero bajar sql server 2012 ni tener el servidor arriba porque trabajo en una maquina virtual y mi ram es limitada.

PS PS: Just in case: Esto no da problemas con azure, el sevidor de azure te permite sobreescribir los connection strings desde el mismo panel de administracion

**Comment by claudiosanchez** [comment]
Point taken. Pero by the way, también puedes tener un web.debug.config donde tienes tu configuración dev, y no le haces commit a ese archivo, o si lo incluyes ya que no altera el resultado.

**Comment by eatskolnikov** [comment]
#Themoreyouknow thanks

**Comment by luis-ramirez** [comment]
Fue lo que te dije desde el primer comment :)

**Comment by eatskolnikov** [comment]
@luis-ramirez sorry man, fue que no te entendí ;-;
