### ISSUE TITLE
Poder hacer preguntas a las posiciones.

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#117]
Deberíamos poner que la gente pueda hacerles preguntas a la posición y que se respondan públicamente.

**Comment by RaulMonteroC** [comment]
Algo estilo foro? o QA como stackoverflow?

**Comment by eatskolnikov** [comment]
Algo más como hace ebay y amazon, tu escribes una pregunta, el pana la responde y todo el mundo puede ver tu pregunta y la respuesta del pana en el detalle de la posicion.

**Comment by RaulMonteroC** [comment]
Eso me parece bien interesante.

**Comment by hminaya** [comment]
disqus?

**Comment by eatskolnikov** [comment]
@hminaya eso podría funcionar pero el problema es que cuando comentas en disqus no se notifica al que postea por defecto. Tendríamos que hacer algo con el API de disqus or something. Cabe la pregunta, ¿qué sería mejor?

**Comment by jgtaveras** [comment]
@eatskolnikov aparentemente disqus si notifica al author, pero estariamos dependiendo de que cada persona habilite esas notificaciones en su perfil

https://help.disqus.com/customer/portal/questions/9644505-does-disqus-sends-email-notifications-to-author-about-new-posts-in-his-thread-

**Comment by amhed** [comment]
:+1: For Feature
:+1: For using Disqus

**Comment by hminaya** [comment]
No creo que valga la pena ponerse a inventar un motor de comentarios, con disqus y que cada quien lo pueda configurar a su manera como dice @jgtaveras deberia ser suficiente.
