### ISSUE TITLE
Parsear las url en las descripciones de las posiciones

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#118]
La idea es que si hay una url en el texto se convierta en un anchor. Por ejemplo en este anuncio http://empleado.azurewebsites.net/JobOpportunity/Detail/27 

Mandan a ir a este link https://github.com/claudiosanchez/QBank pero no puedo hacer click, así que tengo que copiar y pegarlo ;-;

**Comment by luis-ramirez** [comment]
Estoy trabajando en un parser para mostrar de manera mas apropiada la descripcion de una vacante, so, deja meterle eso :) :+1:

**Comment by luis-ramirez** [comment]
Resuelto en PR #116
