### ISSUE TITLE
Setear los meta tags de open graph

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#119]
Estos son los meta tags de og:title, og:description, og:type, og:url y og:image y sirven para mejorar el SEO y para que cuando compartan un link en facebook se vea kawaii.

**Comment by luis-ramirez** [comment]
referencias para el que no sabe que es un meta tag y que es el termino SEO en HTML :)

**Comment by eatskolnikov** [comment]
Esto es opengraph http://ogp.me/ 
SEO significa Search Engine Optimization y es lo que se hace para que el contenido aparezca en los motores de búsqueda como google, bing y altavista
Aquí sobre og + seo https://www.quora.com/Do-OpenGraph-meta-tags-have-an-impact-on-SEO

**Comment by luis-ramirez** [comment]
nice!

**Comment by luis-ramirez** [comment]
Resolveras esto @eatskolnikov ?

**Comment by eatskolnikov** [comment]
Si

**Comment by eatskolnikov** [comment]
done in PR https://github.com/developersdo/empleo-dot-net/pull/125
