### ISSUE TITLE
¿Permitir al empleador sugerir más categorías?

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#122]
Tiene signos de preguntas porque en verdad no sé si sería un buen feature. Digan lo que piensan al respecto.

**Comment by RaulMonteroC** [comment]
Yo diria que ese es un feature que deberia provenir desde los mismos usuarios de la aplicacion. En caso de que lo necesiten, pues que se solicite, asi nos aseguramos que sea algo que de verdad se va a utilizar.

**Comment by eatskolnikov** [comment]
Yo quiero sugerir la categoría "Pasantía"

**Comment by eatskolnikov** [comment]
Voy a abortar esto

**Comment by claudiosanchez** [comment]
La pasantía es una buena sugerencia como categoría nueva
