### ISSUE TITLE
Soporte para markdown en el detalle del puesto

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#124]

**Comment by luis-ramirez** [comment]
se podría introducir este tool para así permitir que los usuarios usen markdown a la hora de publicar un empleo

https://github.com/Knagis/CommonMark.NET

**Comment by eatskolnikov** [comment]
A mi me gusta el markdown de github #justsaying

**Comment by eatskolnikov** [comment]
Estos son mas sugerencias, no he probado ninguno ni se si son mejores pero more is better, right? http://nugetmusthaves.com/Tag/Markdown

**Comment by luis-ramirez** [comment]
Segun CommonMark.NET ellos son mas rapidos

## Performance

Using a simple tool to compare the performance of various Markdown implementations for .NET yields the following results:

 CommonMark.NET 0.4.1      4 ms   7%      

CommonMarkSharp 0.3.2     30 ms   46%
   MarkdownSharp 1.13     55 ms   84%     (might not conform to CommonMark specification)
     MarkdownDeep 1.5      7 ms   11%     (might not conform to CommonMark specification)
  MoonShine (sundown)      3 ms    6%     (wrapper for a native x86 .dll)
             Baseline     65 ms   100%    (used to compare results on different machines)

This benchmark is very simple and tests the processing of the CommonMark specification document itself (a 115 KB file). The results are provided just for a high-level comparison.

**Comment by eatskolnikov** [comment]
Me compró

**Comment by jgtaveras** [comment]
Creen que MD sea el mejor formato tomando en cuenta que personas no tecnicas quizas no lo conoscan ??

**Comment by claudiosanchez** [comment]
Mi opinión es que podemos hacer un hibrido donde por defecto no sea ningún markup, pero que haya una opción de seleccionar un formato como MarkDown o Rich Text Format, etc

La otra cosa es tener varias secciones para así categorizar la información. Que no sea un solo campo donde se pone de todo.

**Comment by luis-ramirez** [comment]
Lo que se quiere en verdad es darle el soporte, osea, 

Jose va a publicar una vacante en emplea.do
Jose usa MD en su dia a dia haciendo PR y demas cosas
Jose quisiera usar MD para que su puesto se vea bonito cuando el lo ponga
Como emplea.do soporta MD en la descripcion del puesto, Jose se aprovecha de esto y usa MD
Como se ve atractiva la descripcion del trabajo, a Jose le llegan muchos CV

se inteligente como jose usa MD. :)

**Comment by luis-ramirez** [comment]
BTW, el template tiene una clase que se llama **text-area** que te permite darle formato rich, lo que pasa es que genera HTML y cuando se somete el form MVC grita y dice que se esta inyectando HTML.

**Comment by amhed** [comment]
No pierdan el foco de quien es el público. Un gerente de HR en Santo Domingo no va a saber lo que es Markdown. 

Quizás algo como Ace Editor con el toolset más sencillo sea lo mejor para alguien llenando un puesto...

**Comment by amhed** [comment]
No nos perdamos en "Agregar vainas chulas porque si", agreguemos cosas que le agreguen valor a quien esté usando la herramienta

**Comment by hminaya** [comment]
+101 for @amhed

**Comment by amhed** [comment]
Yo digo que cerremos este. Tenemos un sistema de votos para decidir en que trabajar/en que no?

Cuantos votos se necesitan para marcar un issue como "Won't fix"?

**Comment by luis-ramirez** [comment]
La idea central del feature no es decirte, ~~"Hey si quieres darle estilo tienes que aprender MD"~~, no, la idea es dar la posibilidad de que si sabes MD puedas aprovechar eso a la hora de publicar la oferta y usarlo el campo **Descripción**

**Comment by claudiosanchez** [comment]
Entiendo que lo dice @amhed es que un Rich Editor (que ya existe en el template) es mucho más natural para un usuario no técnico que MD format.

-1 para MarkDown (Si es hipster)
+1 para Rich Editor

**Comment by hminaya** [comment]
-1 para @claudiosanchez 
+1 para @luis-ramirez 

Nah, y pizza y refresco para mi

**Comment by amhed** [comment]
@luis-ramirez Si nadie lo está pidiendo, no hay necesidad de hacerlo: 

- Cuando tengamos clientes usando la plataforma hacemos preguntas
- Cuando tengamos algo como Mixpanel, KissMetrics, Google Analytics (o cualquiera de las 2,000 ofertas que hay) podemos medir si la gente llega al post y no sabe que escribir, y ahi buscamos que mejorar
- Cuando tengamos clientes podemos hacer pruebas de AB testing usando algo como Optimizely

No se... veo esto más como un problema a atacar desde la perspectiva de producto, no de development. Lo voy a marcar como cerrado por ahora hasta que tengamos data real desde donde tomar decisiones. :bowtie:
