### ISSUE TITLE
Crear proyecto de unit tests

### ISSUE THREAD

**Issue by EfrainReyes** [developersdo/empleo-dot-net#126]
El src deberia tener una suite de tests que pruebe el código de la aplicación.

Estoy creando un issue para que decidamos las librerias a usar en nuestra test suite. Yo puedo abrir un PR despues con el proyecto creado y algunos tests de ñapa.

Yo propongo:

- NUnit 2.x con FluentAssertions
- NSubstitute para mocking

Por qué NUnit 2.x? La versión 3 salió en Noviembre, pero el soporte de los test runners es relativamente limitado:
- Si usas resharper para correr los tests, tiene que ser version 10.0.2+
- Si usas una extension de VS, hay que descargar una que es exclusiva para NUnit 3 (distinta a la clásica para correr tests de NUnit 2.x)
- Otros test runners todavia no soportan v3.

Ahora bien si el consenso es que mejor nos vamos con v3 porque es más reciente, no me voy a oponer.

Por qué NSubstitute y no algo como Moq? Llevo un año trabajando con NSubstitute, y me la encuentro mucho más sencilla y fácil de aprender y de usar que Moq. Además está muy bien documentada.

De nuevo, la idea de crear este issue es que haya una conversación en caso de que la gente quiera proponer alternativas.

**Comment by eatskolnikov** [comment]
Yo no me opongo

**Comment by luis-ramirez** [comment]
Sería súper cool ir probando porque se están introduciendo muchas cosas nuevas y no se esta probando prácticamente nada.

**Comment by EfrainReyes** [comment]
Claro luis. No es que yo este diciendo hey vamos a hacer todos los tests que corresponden ahora mismo, sino, tengamos este proyecto habilitado, y que la gente vaya escribiendo tests para la funcionalidad que no tiene tests todavia.

Ya en un futuro mas a mediano plazo se pudiera decidir si se va a exigir tener tests en los PR.

**Comment by RaulMonteroC** [comment]
De mi parte lo veo bien.

**Comment by claudiosanchez** [comment]
@EfrainReyes Algo a tener en cuenta es que si nos mudamos a ASP.NET vNext, no se si eso afecta el package de testing que elijamos.

**Comment by EfrainReyes** [comment]
Creo que lo unico que afectaria es si se quiere usar .NET Core para correr la app en linux o en osx, pero me parece que de todos modos hay implementaciones multiplatform de NUnit (recuerdo que en Xamarin uno usaba NUnit Lite).

**Comment by luis-ramirez** [comment]
#132
