### ISSUE TITLE
Usar C# 6 en el proyecto

### ISSUE THREAD

**Issue by EfrainReyes** [developersdo/empleo-dot-net#127]
Como un task de technical debt, propongo que empecemos a usar C# 6 en el proyecto. Es un upgrade que es relativamente painless y como este proyecto no es una libreria que mucha gente anda usando en multiples versiones de .NET ni nada por el estilo, podemos darnos el lujo de hacerlo.

Esto nos da algunos beneficios:

- Estamos al día con las actualizaciones que vienen en C# 6, y nos podemos beneficiar de los features nuevos.
- Los contribuyentes con VS tendrian que utilizar VS 2015. Así evitaríamos diffs en pull requests donde el solution file sea modificado porque el submitter uso VS 2013. No es que sea una solucion permanente al problema (i.e no garantiza que cuando salga una nueva version de VS no volvera a pasar lo mismo), pero ayudaria.

**Comment by claudiosanchez** [comment]
+1 para esta. Visual Studio 2015 Community Edition es gratis.

**Comment by RaulMonteroC** [comment]
Apoyo esta idea. C# 6.0 nos da buenos features y hacer el cambio no implica cambios bruscos.
