### ISSUE TITLE
Actualizar el readme.md

### ISSUE THREAD

**Issue by jgtaveras** [developersdo/empleo-dot-net#128]
Actualmente el readme no refleja lo que entiendo es el proposito del proyecto, deberiamos actualizarlo

**Comment by wistcc** [comment]
@jgtaveras que cosas entiendes que faltan?

**Comment by eatskolnikov** [comment]
@jgtaveras bump!

**Comment by hminaya** [comment]
@jgtaveras arranca...

**Comment by hminaya** [comment]
@jgtaveras a parte del proposito tambien incluye el setup inicial del proyecto, por mas sencillo que sea.

**Comment by hminaya** [comment]
y como contribuir.

**Comment by claudiosanchez** [comment]
Pizza and Soda are always welcomed!

**Comment by Willjobs94** [comment]
I guess we can close this Issue  thank of this pull request #347
