### ISSUE TITLE
Usar MVC6 (vNext)

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#130]
Ya que se pretende modernizar el proyecto y usar C# 6 (#127), me parece razonable sugerir utilizar MVC 6 (vNext). MVC 6, aunque no ha sido lanzado en su version final esta en una etapa suficientemente madura para ser usado en un proyecto de este tipo. Ademas de que segun su roadmap, la version final viene en el primer cuatrimestre de este año.

Actualizar a vNext traeria los siguientes beneficios:

- Poder usar el nuevo Project.json y evitar los problemas de diff por versiones diferentes de VS.
- Poder colaborar sin necesidad de usar Windows.
- Poder hostear el proyecto sobre Linux sin limitaciones.

**Comment by codnee** [comment]
Pasos a tomar:

[ ] Eliminar las carpeta .nuget y vs/config.
[ ] Migrar el projecto al nuevo formato ( project.json ) e incluir en este las dependencias.
[ ] Actualizar las dependencias para usar MVC 6 y pasar los using statements a los nuevos namespace.
[ ] Crear la carpeta wwwroot y mover los archivos estaticos y Web.config a esta.
[ ] Hacer refactor a la clase Startup. No mas App_Start, la inicializacion se realizara en esta clase.
[ ] Arreglar los errores que aparezcan.

Luego de tener MVC6 corriendo se podria planear la migracion a EF7.

**Comment by hminaya** [comment]
I'll take this one. Les aviso cuando vaya a comenzar (next week) para que hagan una breve pausa en el branching....

**Comment by EfrainReyes** [comment]
Sugiero crear un proyecto nuevo en vez de tratar de actualizar el existente. Idealmente esto se haría después de que @jgtaveras realice #140 

cc @claudiosanchez @luis-ramirez

**Comment by hminaya** [comment]
@EfrainReyes que ventaja tendria crear un proyecto nuevo vs mover/editar/borrar archivos en el proyecto existente?

**Comment by EfrainReyes** [comment]
1. Nadie tendría que pausar el branching en lo que completas la migración. Se pueden ir empujando features nuevos o bug fixes en lo que creas el proyecto y migras los features existentes.
2. La estructura del proyecto es completamente diferente. Cuando creas un proyecto de ASP.NET 5, VS hace mucho trabajo por tí (project.json, setear los task runners). Hacer eso a manopla va a ser mucha lucha.
3. [Es lo que recomienda la documentación](http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/migration/migratingfrommvc5.html). Si eso lo dice la documentación oficial, he de suponer que será más lucha de la necesaria el intentar hacer eso a mano.

**Comment by hminaya** [comment]
@EfrainReyes 

Entiendo todo lo que dices y estoy de acuerdo. Solo una pregunta. Entiendo que de igual forma tendrian que "pausar" el branching por un momento, aunque sea un dia. Ya que despues que suba el nuevo no van a poder hacerle merge si el branch que hicieron esta basado en una copia del master viejo.

O hay algo que no este viendo?

**Comment by EfrainReyes** [comment]
En verdad creo que no habría tanto problema en parar los PR por un día, no se están haciendo muchos pull requests de todos modos y lo que habría que portar al site nuevo no es mucho.

Por cierto, ojo con esto: http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx

**Comment by hminaya** [comment]
Acabadito de salir del horno, gracias @EfrainReyes. Voy a coordinar esto.

**Comment by RaulMonteroC** [comment]
La conclusión final sobre este tema es que no se va a realizar la migración hasta que el .net core este maduro. Cerrare este issue.

**Comment by codnee** [comment]
No seria mejor tener un tag que indique que no se hará ahora (ej: "backlog" | "waiting for .net core" )?
