### ISSUE TITLE
Duh! Search feature 

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#131]
Cuando los jobs sean más de 50; como vamos a poder buscar lo que nos interesa?

Como usuario, quiero buscar por keyword (full text search) y que los resultados de la busqueda sean desplegados en la lista.

**Comment by luis-ramirez** [comment]
**100%** de acuerdo contigo
[Aquí](http://manfred-ramoser.blogspot.com/2009/09/full-text-search-for-entity-framework.html) hay un ejemplo de como implemetar un FTS virtual con EF

**Comment by luis-ramirez** [comment]
Le di a esto

**Comment by claudiosanchez** [comment]
Dale! (Como dice Pitbull). 
En un futuro un feature más complejo puede usar otra vaina más hipster para hacer search.

**Comment by luis-ramirez** [comment]
Done in PR #135
