### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#134]
la verdad es que quien quiere tener "yet another username and password" para tener que publicar un trabajito de vez en cuando. 

Al rescate viene FB, Twitter y Google ID.  En par de clicks ya estás publicando, y con el valor agregado de que tienes un Graph (en el caso de FB) para crear features sociales en un futuro.

**Comment by RaulMonteroC** [comment]
Esto esta en el issue #99.
