### ISSUE TITLE
Cambiar la pocision del icono del menu hacia la izquierda

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#137]

**Comment by jgtaveras** [comment]
@luis-ramirez coloca un screenshot para identificar donde es esto

**Comment by luis-ramirez** [comment]
![screen shot 2016-01-09 at 1 23 04 pm](https://cloud.githubusercontent.com/assets/6517152/12217356/0f4467fa-b6d4-11e5-8d49-a174cd4b7944.png)

**Comment by luis-ramirez** [comment]
pr #147
