### ISSUE TITLE
Poner logo placeholder 

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#139]
Thanks Raylin D. Aquino ![emplea do](https://cloud.githubusercontent.com/assets/1693000/12214024/d8734fc0-b65b-11e5-9643-cf732dc8946f.png)

**Comment by jgtaveras** [comment]
@eatskolnikov donde debe de ir este logo ??

**Comment by eatskolnikov** [comment]
@jgtaveras  hay que ponerlo en la carpeta de assets y poner la url en el content del meta tag og:image

**Comment by jgtaveras** [comment]
I'll take this one

**Comment by claudiosanchez** [comment]
@jgtaveras ¿Como vamos? Te ayudo? Pair programming?

**Comment by jgtaveras** [comment]
@claudiosanchez creo que no es necesario, solo que el issue no era tan descriptivo

**Comment by eatskolnikov** [comment]
@jgtaveras ¿cómo vamos? Tienes este y el #140. Call dibs on one at a time unless they are related :v :v

**Comment by jgtaveras** [comment]
@eatskolnikov pull request done, el #140 esta programado para un pair programming session

**Comment by eatskolnikov** [comment]
@jgtaveras pero entonces va a haber que crearles cuentas en disqus (que no van a hacer) y es como que ya mejor lo hacemos en el site.
