### ISSUE TITLE
Mover clases core a un class library separado

### ISSUE THREAD

**Issue by EfrainReyes** [developersdo/empleo-dot-net#140]
En anticipación al upgrade a ASP.NET 5, deberíamos ir moviendo las clases que no dependen del framework (como repo classes, DTOs y configuracion de EF) a un assembly separado, para que cuando creemos el proyecto en vNext sea sencillo mover la funcionalidad al proyecto nuevo.

**Comment by jgtaveras** [comment]
i'll take this one

**Comment by luis-ramirez** [comment]
:+1:  @EfrainReyes

**Comment by codnee** [comment]
La configuracion de EF es no deberia ir en una libreria aparte. En MVC 6 se hace uso intensivo de dependency injection, al tener la configuracion de EF fuera de la libreria esta se podria usar en la aplicacion movil que se haga despues.

**Comment by EfrainReyes** [comment]
No entiendo qué tiene eso que ver.

- Como así que por que MVC6 use DI tiene que estar en la misma librería? No sé cómo será con el IoC que MVC6 trae por default pero en muchos IoC containers de terceros se pueden separar las definiciones en módulos. Por ejemplo Ninject los llama NinjectModules, StructureMap los llama Registry. Las definiciones no tienen que estar en un solo proyecto, y si el IoC default de MvC6 no lo hace, se puede usar uno de un tercero perfectamente.
- Con lo de la app móvil, este concern lo entiendo: que porque uno tenga EF en una librería aparte entonces la app movil no pudiera usar esa libreria. Pero en ese caso solo hay que crear una PCL aparte cuando llegue el monento de hacer la app movil, y mover alla las clases que la app movil y la app web usen en comun..

**Comment by luis-ramirez** [comment]
@codnee no entendí ni papa :p

**Comment by codnee** [comment]
@luis-ramirez mi comentario era basicamente sobre el segundo punto de @EfrainReyes

**Comment by luis-ramirez** [comment]
Pero porque no debería? Es lo que no entiendo, por que EF no puede estar separado?

**Comment by codnee** [comment]
No es que no pueda, es que romperia la forma tipica de hacer las cosas en MVC 6. En MVC 6 se configuran las dependencias en una clase Startup:

``` C#
public class Startup
{
//... More stuff here.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFramework().AddNpgsql()
                .AddDbContext<ApplicationDbContext>(options =>
                options.UseNpgsql(Configuration["Data:DefaultConnection:ConnectionString"]));
        }
}
```

Y estas son inyectadas en el constructor del controller:
``` C#
public class XController
{
        ApplicationDbContext db;
        public XController(ApplicationDbContext c)
        {
            db = c;
        }
}
```

Las configuraciones de esas dependencias se cargan de un archivo de configuracion, durante la inicializacion de la aplicacion. Citando [la documentacion:](http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/migration/migratingconfig.html)

"The web.config file has also been replaced in ASP.NET 5. Configuration itself can now be configured, as part of the application startup procedure described in Startup.cs. Configuration can still utilize XML files, but typically ASP.NET 5 projects will place configuration values in a JSON-formatted file, such as appsettings.json. ASP.NET 5’s configuration system can also easily access environment variables, which can provide a more secure and robust location for environment-specific values. This is especially true for secrets like connection strings and API keys that should not be checked into source control."

**Comment by luis-ramirez** [comment]
Pero que importa separar EF del proyecto principal? básicamente estas diciendo que si tengo ahora mismo un proyecto en MVC5 que tiene EF en otro project porque se comparte con otro Front-end no podré migrar a MVC6 porque MVC6 no funciona con EF en otro proyecto y eso no es así.

De que todos los ejemplos de MVC en las sites de MSFT (medio malos por cierto) tengan el front-end junto con el back-end core no quiere decir que sea así.

**Comment by codnee** [comment]
Solo hablo de la configuracion de EF y nunca dije que no se puedia, solo que no se debia. 

Pensando en la situacion de tener 2 front-ends se podria tener una clase Startup en la libreria que configure las dependencias compartidas, y que cada uno de los front ends tenga su clase Startup heredando del Startup de la libreria.

**Comment by codnee** [comment]
Por si acaso estamos en páginas diferentes, a que ustedes le llaman Configuración de EF?

**Comment by hminaya** [comment]
No hay ningun problema con separarlo. Debe ser asi. @jgtaveras Confirmas que vas a trabajar esto?

**Comment by EfrainReyes** [comment]
@jgtaveras ¿cómo vamos? :joy:

**Comment by hminaya** [comment]
@jgtaveras esta preso

**Comment by claudiosanchez** [comment]
¿Se va a dar el meeting del 26 De Enero entonces?

**Comment by carlosvasquez** [comment]
Los mirones podemos estar en meeting?

**Comment by RaulMonteroC** [comment]
A que hora sera?

**Comment by hminaya** [comment]
@claudiosanchez what meeting?
