### ISSUE TITLE
Los vídeos de Aprendizajes estan privados

### ISSUE THREAD

**Issue by josegomera** [developersdo/empleo-dot-net#141]
Estos videos estan privados, quisiera saber si hay otra forma de verlos o de obtener esa informacion.

https://github.com/developersdo/empleo-dot-net/wiki/Sesiones-de-Trabajo-Previas

**Comment by eatskolnikov** [comment]
Subanlos a [streamelopers](https://streamelopers.org) :v

**Comment by AIsaac08** [comment]
+1

**Comment by EfrainReyes** [comment]
@josegomera puedes confirmar si ya se ven los videos? Acabo de revisar en Chrome incognito y se ven.

**Comment by josegomera** [comment]
Gracias ya se pueden visualizar los videos

**Comment by DCruz22** [comment]
Solo se han hecho las sesiones que aparecen [aqui](https://github.com/developersdo/empleo-dot-net/wiki/Sesiones-de-Trabajo-Previas]) o existen mas?
