### ISSUE TITLE
Ideas para un nuevo Logo

### ISSUE THREAD

**Issue by rafaelmedian** [developersdo/empleo-dot-net#143]
![logo_emplea-dot-net-03-01](https://cloud.githubusercontent.com/assets/5257843/12219253/b671fe7e-b711-11e5-8641-277e7159be5c.jpg)

> Logo simple con una lupa, haciendo referencia a la busqueda en el sitio.
# *****************************************************

![logo_emplea-dot-net-03-02](https://cloud.githubusercontent.com/assets/5257843/12219254/c2f7ba6c-b711-11e5-9396-e1de316399a3.jpg)

> Suitcase en forma de hoja de papel con una lista o texto, haciendo referencia a la lista de trabajos

**Comment by eatskolnikov** [comment]
@zxhadow Son propuestas para el logo de la plataforma o son iconos?

**Comment by zxhadow** [comment]
@eatskolnikov Son logos, solo que no habia se ha tipografia aun

![logo-02](https://cloud.githubusercontent.com/assets/5257843/12219417/d7bbb88e-b718-11e5-8e1a-e6f4ca9799a0.jpg)

**Comment by claudiosanchez** [comment]
@zxhadow Están jevi todos.  ¿Cuales crees que deben ser los design hints del logo de Emplea.do? 
- Lista de empleos
- Tech in nature 
- Remote?

**Comment by zxhadow** [comment]
@claudiosanchez 
Emplea.do siempre su enfoque seran ofertas de tecnologia? 
No queremos enfocarlo solo a RD?

A que nos referimos con tech in nature?

Remote creo que no es el enfoque principal, pero puede ser jevi.

**Comment by eatskolnikov** [comment]
@zxhadow Es un board de trabajos de tecnología, no tiene que limitarse a RD

**Comment by claudiosanchez** [comment]
Como vamos?

**Comment by zxhadow** [comment]
@claudiosanchez Estaba pausado, lo continuamos este fin de semana

**Comment by claudiosanchez** [comment]
@zxhadow: Algún update sobre esto?

**Comment by RaulMonteroC** [comment]
Se me ocurrio esto. Como lo ven? No soy un artista pero el concepto es un maletín entre dos llaves. Si les gusta la idea pueden ponerle el maquillaje.

![](https://app.box.com/s/14e8lmjwgpjgiicczpw3u1a7rwa1oph4)

**Comment by eatskolnikov** [comment]
@RaulMonteroC ese dibujo está para ponerlo en la puerta de la nevera :eyes:

**Comment by DCruz22** [comment]
Who says developers can't draw? :v

**Comment by RaulMonteroC** [comment]
@eatskolnikov jajajajajaja tas pasao.

Lo hice para que tomen la idea de referencia y lo pongan chulo. Me gusta más ese concepto a una lupa o una hoja. :stuck_out_tongue:

**Comment by jugomez** [comment]
Proposals for new logo

![emplea dothin-2](https://cloud.githubusercontent.com/assets/3052715/13207438/bc08316a-d8e4-11e5-8b4d-989b68c826a5.png)
![emplea dobold-2](https://cloud.githubusercontent.com/assets/3052715/13207439/bc0b0fca-d8e4-11e5-94b1-4b3f3e3af4a4.png)
![emplea dothin](https://cloud.githubusercontent.com/assets/3052715/13207440/bc0eca5c-d8e4-11e5-8fbe-c9c693a5be0f.png)
![emplea dobold](https://cloud.githubusercontent.com/assets/3052715/13207441/bc101934-d8e4-11e5-9f8d-be34b1e772e2.png)

**Comment by Edulopez** [comment]
@jugomez Siento que esta muy Internet explorer y que la tipografía no va con el estilo/feeling del site.

**Comment by jugomez** [comment]
@Edulopez ya viste el nuevo template que se esta creando? http://empleado-template.azurewebsites.net/
Es la tipografía que se esta utilizando. y no estoy de acuerdo con la similitud de internet explorer https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=630&q=internet+explorer&oq=intern&gs_l=img.3.1.0l10.1042.2641.0.3727.8.7.1.0.0.0.208.780.4j2j1.7.0....0...1ac.1.64.img..0.8.789.9bP6b5EAq5k
 
Pero lo de la E lo voy a cambiar porque no he visto otro comentario mas que eso se parece a "internet explorer"

**Comment by jugomez** [comment]
Otra versión 
![emplea dobold2](https://cloud.githubusercontent.com/assets/3052715/13225464/59de65a2-d963-11e5-82c7-b35b15127170.png)

**Comment by jugomez** [comment]
Otra versión
![emplea dobold3](https://cloud.githubusercontent.com/assets/3052715/13225873/384ecf2e-d965-11e5-9163-1a31a63cb97c.png)

**Comment by ange1uis** [comment]
Saludando, aquí les comparto un concepto que esta muy relacionado al tipo de ofertas que predominan en emplea.do. Claro que si la plataforma se expandirá a otras áreas este no las engloba pero se puede mejorar para el fin.

![empleado-logo-1](https://cloud.githubusercontent.com/assets/3917586/14808459/3faeec5c-0b53-11e6-9584-23d9c7b9a8b0.png)
