### ISSUE TITLE
Definir si es necesario una entidad que represente una Empresa

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#15]
Según el modelo de emplea.do, no se crean empresas, osea, la empresa es una parte directa de la entidad JobOpportunity(o como le queramos llamar), entonces, es necesario crear una entidad Company?

**Comment by RaulMonteroC** [comment]
Creo que ya es el momento adecuado de separar esta entidad, pues se inicia el proceso de manejo de usuarios, de acuerdo al issue #79

**Comment by RaulMonteroC** [comment]
Cerrare esta pregunta. Si surge alguna duda nuevamente, se abrirá otro issue
