### ISSUE TITLE
Hacer que el formulario de creación de propuestas sea como un wizzard

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#151]
Para ver si mejora el ux de la gente de HHRR. Voy a poner el formulario de creación de posición para que se vea mas o menos como este:

https://dribbble.com/shots/1761180-Responsive-Full-Screen-Form

**Comment by RaulMonteroC** [comment]
Eso esta muy cool.

**Comment by DannyFeliz** [comment]
Cool! :+1:

**Comment by eatskolnikov** [comment]
https://github.com/developersdo/empleo-dot-net/pull/207
