### ISSUE TITLE
Configurar un hosted CI Server que corra con cada Pull Request

### ISSUE THREAD

**Issue by hminaya** [developersdo/empleo-dot-net#153]
La idea es que corra los tests de forma automatica y haga un deployment a algun staging environment.

Opciones:

* https://travis-ci.org
* https://circleci.com
* Otros?

**Comment by luis-ramirez** [comment]
Actualmente como esta aparcado en un azure website tenemos configurado con github

**Comment by eatskolnikov** [comment]
https://www.jetbrains.com/teamcity/
https://jenkins-ci.org/

**Comment by claudiosanchez** [comment]
En general totalmente de acuerdo. Algo que se debe hacer es hacer un gap analysis de los CIs para entender que limitaciones especificas a nuestra solución pueden tener. 

Jenkins y Team City son bien poderosos, pero entonces se tienen que hostear en un Server (Yo tengo uno, by the way) pero es más envuelvo que si lo hosteamos en la nube.

**Comment by hminaya** [comment]
No necesariamente tiene que hostearse en un VPS. Puede hacerse en la nube y utilizar un CI. Es mas bien para que cuando alguien haga un pull request se haga el check automatico de que corrieron todos los tests y se pueda ver de una vez, antes de yo bajar ese codigo a mi maquina y probarlo.

Por ejemplo miren este pull request, ahi se ve que paso un build de Travis (CI Server), corrio todos los tests y cualquier otro check que se quiera hacer.
![screen shot 2016-01-14 at 8 02 23 pm](https://cloud.githubusercontent.com/assets/586656/12341700/d60e8f40-baf9-11e5-85d7-568220133b7e.png)

**Comment by codnee** [comment]
Algo a tomar en cuenta es que Travis solo se puede usar si el proyecto puede correr en Mono.

**Comment by Willjobs94** [comment]
@eatskolnikov can we close this issue ?

**Comment by hminaya** [comment]
Not yet. Ya iniciamos, no se ha terminado.

**Comment by Willjobs94** [comment]
Roger!
