### ISSUE TITLE
Agregar Beneficios y Requisitos en campos separados

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#155]
Al momento de registrar una vacante, dar la posibilidad al usuario de colocar por separado los beneficios y los requisitos del puesto para asi poder mostrar de una manera mas coherente el detalle de un puesto.

**Comment by DCruz22** [comment]
Esto se ha trabajado?

**Comment by eatskolnikov** [comment]
@DCruz22 Si es un issue abierto, no se ha trabajado.

**Comment by anyeloamt** [comment]
@DCruz22 Estás metiendo mano con eso?

**Comment by DCruz22** [comment]
Si @anyeloamt, Creo que hoy hago el PR
