### ISSUE TITLE
Informacion de la empresa

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#156]
Posibilidad de colocar mas detalles acerca de la empresa que ofrece el puesto

- Redes Sociales
 - FB
 - Twitter
 - Etc

- Descripcion sobre la empresa
- Un video si lo posee
- Direccion
- Telefono

**Comment by RaulMonteroC** [comment]
Esto se puede añadir como campos al perfil de usuario descritos en el issue #100. Cerrare este y añadire esta información alla.
