### ISSUE TITLE
Buscar vacantes

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#158]
Quisiera como usuario poder encontrar de una forma mas facil un puesto, por ende quisiera ver algo como esto para buscar

<img width="653" alt="screen shot 2016-01-14 at 3 31 21 pm" src="https://cloud.githubusercontent.com/assets/6517152/12335094/d1a65f80-bad3-11e5-8c02-40a078b26f93.png">

**Comment by luis-ramirez** [comment]
Site de referencia

http://careers.stackoverflow.com/

**Comment by claudiosanchez** [comment]
Propongo que esto se rompa en varios issues:
* Buscar por keyword 
* Buscar por Location (debe de tomar en cuenta Geo cercanía y otros atributos que hacen esto un feature más complejo que un "text" search) 

Buscar por keyword es un mango bajito. Buscar por location es más envuelto.

**Comment by hminaya** [comment]
Propongo que el buscar no se vuelva un formulario con 14 textbox, 21 dropdown y 49 checkboxes. Se haga por separado como dice @claudiosanchez o junto, pero que no se vuelva complicado.

Yo fuera feliz con algo parecido a la imagen que puso @luis-ramirez o mas simple.

**Comment by luis-ramirez** [comment]
Actualmente se busca por esos campos (tanto keyword como location) la idea es hacer la busqueda mas agradable para el usuario y colocar esto en el home page
