### ISSUE TITLE
Posibilidad de agregar tags a un job

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#16]
La posibilidad de agregar un sistema de tags a la hora de crear un Job seria de gran ayuda, pero, este podría ser un feature posterior, que opinan?

**Comment by jeanrodriguez** [comment]
@amhed  para este issues, que hay q tener en cuenta, osea se creara una tabla para almacenar los tags, como es mas o menos que se hara eso

**Comment by amhed** [comment]
1. Agregas una entidad llamada Tag
1. Agregas las relaciones necesarias: un job opportunity tiene de cero a muchos tags, un tag puede pertenecer a 1 o muchos jobOpportunities. 
1. Agregas una migración para definir a tabla en la BD
1. Creas las pantallas necesarias

Creo que se puede dividir en dos: una para las estructuras de datos, y otra para dibujar las pantallas necesarias

**Comment by jeanrodriguez** [comment]
ok. la entidad tag solo tendra como propiedad id y nombre, o tambien le pongo descripcion por si quieren poner algo mas.

**Comment by amhed** [comment]
Yo no veo necesidad de que tenga más de Id y Nombre. Comencemos con lo simple y vamos mejorando en el camino

**Comment by jeanrodriguez** [comment]
ok, cool

**Comment by jeanrodriguez** [comment]
@amhed yo pensando pero la relacion de joboportubity a tag no deberia de ser mucho a mucho??

**Comment by jeanrodriguez** [comment]
para que se cree la tabla con las relaciones de joboportunity_Tags

**Comment by amhed** [comment]
Si, many to many con una tabla intermedia que no se refleja en el Entity Model, pero que se crea en SQL

**Comment by jeanrodriguez** [comment]
Exactooo :)

**Comment by jeanrodriguez** [comment]
@amhed  estoy teniendo problema para el create de tag no se porque veo todo bn y el pase de savechange pero no me guarda en la base de datos.

el update lo hace bn y todo nitido

**Comment by amhed** [comment]
Tiene que dar más detalle de ahí compadre :)

**Comment by jeanrodriguez** [comment]
jeje, hago un pull request para q veas?

**Comment by amhed** [comment]
Si

**Comment by amhed** [comment]
O sea, cual es el error?

**Comment by jeanrodriguez** [comment]
ese es el detalle no me da error,

**Comment by jeanrodriguez** [comment]
le voy a dar el pull reuest para que veas como hice para las relacion many to many

**Comment by amhed** [comment]
Pon el PR, yo lo reviso mañana que hoy no puedo

**Comment by jeanrodriguez** [comment]
cool

**Comment by jeanrodriguez** [comment]
@amhed para los mantenimiento para el delete voy a crear un enum llamado Estado ej, activo, inactivo. Para no tener que borrar el registro de la base de datos.

**Comment by amhed** [comment]
Pon un atributo booleano en la entidad que se llame "IsDeleted" o algo así.

O no, como dices es mejor. Crea un enum. Algunos de los atributos deberían
ser: creado, publicado, borrado.

Así el usuario puede subir un draft antes de publicar

2015-02-17 13:40 GMT-08:00 Jean Carlos Rodriguez Cedeno <
notifications@github.com>:

**Comment by jeanrodriguez** [comment]
ok, nitido

**Comment by RaulMonteroC** [comment]
@jeanrodriguez como ha quedado esto?

**Comment by eatskolnikov** [comment]
¿Esto es necesario? ya se tienen categorías en los puestos

**Comment by RaulMonteroC** [comment]
Lo interesante de esto es que puede ayudar en la búsqueda. Imagina poder poner tags por las tecnologias utilizadas y la ubicacion por ejemplo. Ya con eso puedes filtrar los trabajos qu realment te interesan.

**Comment by RaulMonteroC** [comment]
Replanteando mi comentario, podemos lograr eso mismo con categorias, keywords y ubicación. Creo que este issue ya no es necesario.
