### ISSUE TITLE
Posibilidad de especificar el tipo de trabajo

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#160]
Agregar dropdown con una lista para especificar el tipo de puesto

<img width="572" alt="screen shot 2016-01-14 at 3 36 24 pm" src="https://cloud.githubusercontent.com/assets/6517152/12335227/726eb0fc-bad4-11e5-9760-5618be9defee.png">

**Comment by DCruz22** [comment]
Si nadie esta en esto me interesa trabajarlo

**Comment by amhed** [comment]
Date que jevi como está en AngelList: 

![image](https://cloud.githubusercontent.com/assets/579291/12379837/2bd11e18-bd28-11e5-8068-604215ec5279.png)

Quizás valdría la pena usar checkboxes?

**Comment by hminaya** [comment]
Vale la pena checkboxes, ya que pueden estar buscando cualquiera de las 2 (o 3, o 4, o X) modalidades.

**Comment by DCruz22** [comment]
Jevi, le di a esto entonces.

**Comment by DCruz22** [comment]
Que piensan de [este](http://harvesthq.github.io/chosen/) plugin para el multi select?

**Comment by amhed** [comment]
Creo que ya estamos usando Select2: https://select2.github.io/examples.html

Si de todas formas lo deseas cambiar: 
- Asegúrate de justificar "por qué" este plugin es mejor
- Actualizar todos los sitios donde se use Select2 por Chosen
- Borrar la referencia a Select2 en el folder `/Scripts` 

(o simplemente usar Select2 que ya está en el proyecto)

**Comment by DCruz22** [comment]
Mala mia por no ver que el proyecto ya usaba uno. Gracias @amhed, me quedo con Select2.

**Comment by anyeloamt** [comment]
Podemos cerrar este issue ya #292

**Comment by Willjobs94** [comment]
@eatskolnikov can we ?
