### ISSUE TITLE
Autorizar las Publicaciones

### ISSUE THREAD

**Issue by hminaya** [developersdo/empleo-dot-net#162]
Al principio cuando http://emplea.do salio las publicaciones eran automaticas, la gente las creaban y se publicaban solas.

Todo hasta que un gracioso puso unos mensajes bien bonitos por ahi a proposito.

Hay que hacer algo, tal vez no manual, pero algo para que no sea tan automatico....

**Comment by Edulopez** [comment]
@hminaya  Esto es común cuando no hay nadie que de la cara por el post

Se me ocurren estas 2 soluciones.

1- autenticar a la persona que esta publicando el job (#134  )
2- Hacer que la comunidad pueda limpiar los jobs. Si la gente puede dar un "downvote" podriamos hacer lago para que después de cierto threshold esta sea eliminada o pasada a otra categoria.  Esto es algo parecido a lo que hace 9gag y el filtro de posts.

**Comment by RaulMonteroC** [comment]
@Edulopez +1 a la idea del downvote (y upvote)

**Comment by delgiudices** [comment]
+1 al Downvote!

**Comment by anyeloamt** [comment]
+1

**Comment by anyeloamt** [comment]
Me gustaría tomarlo.

**Comment by RaulMonteroC** [comment]
@anyeloamt Mete mano.

**Comment by Edulopez** [comment]
@anyeloamt  Estas trabajandolo?

**Comment by RaulMonteroC** [comment]
El issue perse (Aprobación de publicaciones) deja de tener sentido con la implementación de autenticación de usuario. Voy a cerrar este issue y crear uno nuevo con lo discutido aquí. Esencialmente, la parte del downvote y upvote.

**Comment by Edulopez** [comment]
Gj
