### ISSUE TITLE
Custom Error Page 

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#163]
Como usuario, no quiero ver la pagina amarilla por defecto de ASP.NET cuando ocurre un error. 

¿Que les parece esta imagen?

![comopinedax](https://cloud.githubusercontent.com/assets/2293759/12343158/4f4bb3ce-baff-11e5-802d-3e1482bbcc2e.png)

**Comment by luis-ramirez** [comment]
:+1:

**Comment by claudiosanchez** [comment]
+1
