### ISSUE TITLE
Fecha de vigencia de las publicaciones

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#168]
Las publicaciones Deben poseer un tiempo de vigencia a fin de que en el JobOpportunity List se muestren publicaciones recientes.

Por ejemplo: Solo se muestren publicaciones de no más 15 o 30 días desde su fecha de publicación.

**Comment by RaulMonteroC** [comment]
Esto es algo válido. Sin embargo, considero que como no tenemos muchos trabajos publicados aún sería mejor dejarlo tal cual para que la página se vea con contenido. No se viera bien que en algún momento dado tengamos solo tres publicaciones solo porque en un periodo x de tiempo no hubo mucho movimiento, aunque esa fuera la realidad la percepción del usuario final es que casi no se esta usando el site.
