### ISSUE TITLE
Nivel de experiencia requerido

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#169]
Posibilidad de indicar el nivel de experiencia requerido para el puesto.

Ejemplo: 2 años mínimo de experiencia.

**Comment by hminaya** [comment]
Entiendo que no es necesario llegar a este nivel de detalle, si se motiva a la persona a crear una descripción explicita seria mucho mejor. 

Entiendo que un esquema similar a https://weworkremotely.com/jobs/2478-java-software-engineer se ve mucho mejor.

**Comment by luis-ramirez** [comment]
Como dice @hminaya con una buena descripcion se resuelve.

**Comment by claudiosanchez** [comment]
+1 para la sugerencia de @hminaya. 

Una buena "guía" de como escribir un post puede ayudar a los "HR managers" que publican posiciones. Un video tutorial por ejemplo sería una forma de hacer "User Education".

**Comment by jugomez** [comment]
Entendido....
