### ISSUE TITLE
Contador de vistas para una publicación

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#170]
Posibilidad de agregar un contador de vista realizadas a una publicación
- Mostrar contador en el Job Opportunity List
- Mostrar contador en Job Opportunity Detail

**Comment by luis-ramirez** [comment]
+1

**Comment by DannyFeliz** [comment]
+1

**Comment by hminaya** [comment]
+1

**Comment by claudiosanchez** [comment]
+1 si son vistas únicas basadas en un cookie-based approach. i.e.: Que cada vez que se refresque la página no cuente como un view.

**Comment by jugomez** [comment]
@claudiosanchez la idea entonces sera guardar una cookie para que un usuario solo pueda sumar al contador si y solo si es su primera vez visualizándolo?

**Comment by RaulMonteroC** [comment]
Creo que esto ya esta listo o no?

**Comment by jugomez** [comment]
Esta listo y publicado
