### ISSUE TITLE
Permitir la modificación de una publicación

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#171]
Permitir modificar una publicación después de posteada.

Idea: Como en esta versión aún no se implementa el manejo de cuentas, se puede generar un token al momento de guardar una publicación, que entregue al publicante a fin de que si desea realizar la modificación este ingrese el mismo para validar su identidad.

**Comment by claudiosanchez** [comment]
El feature de perfil/autenticación ya está en el pipeline. Este feature tendría un ciclo de vida muy corto de implementarse. 
 -1

**Comment by RaulMonteroC** [comment]
Ya esta implementado el login de usuarios y se creó un issue(#366) para trabajar la edición de trabajos a partir de ese approach. Se cerrara este issue.
