### ISSUE TITLE
Autocomplete de Localidad usando Google APIs

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#173]
Como usuario, no quiero estar limitado a las opciones de un dropdown para localidad. 
- Usando un campo de texto para escribir la localidad, quiero introducir el nombre de la ciudad y que Emplea.do lo autocomplete. 

- Se puede usar el Google Place API para esto.

**Comment by amhed** [comment]
Quizás no es necesario usar el API. Por que no simplemente tener una lista de las ciudades en el país y usar eso?

Cual es la posibilidad de que alguien en Cambita esté buscando un developer? Yo creo que es suficiente con usar las ciudades grandes / keeping it simple

**Comment by hminaya** [comment]
Si mal no entiendo lo que dice @claudiosanchez es guardar el nombre de la ciudad/localidad/pais en un campo texto, el cual va a ser autocompletado por el API en el caso de que lo pueda encontrar. Si no lo puede encontrar, simplemente escribirlo y es transparente para el usuario final.

So, por ejemplo yo pudiera decir:

* Location: Santo Domingo
* Location: Cibao
* Location: Haiti
* Location: Caribe
* Location: USA/Canada

**Comment by claudiosanchez** [comment]
@amhed: El punto principal del feature es no estar limitado por un drop down (como dice Hector); Opcionalmente que puedas introducir el nombre de la ciudad/lugar y sea autocompletada (para eso el Google Place API). Este feature es importantisimo porque permite hacer que este site no sea "local" a RD y que si un pana en Puerto Rico lo quiere usar también pueda. 

+1 para @hminaya por comprensión.

**Comment by jgtaveras** [comment]
para referencia:
https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by claudiosanchez** [comment]
Más info:
Url con los espacios para los tokens. 

 https://maps.googleapis.com/maps/api/place/autocomplete/json?&language=es&types=(cities)&key={apiKey}&input={urlEncodedInput}

**Comment by jugomez** [comment]
Yo opino que estamos evaluando los issues en el contexto de que es una aplicación para un cliente final, donde tratamos de que las soluciones sean lo menos complejas para ahorrar el tiempo y ser más productivos entregando valor (Es lo correcto). Pero según tengo entendido esto es una iniciativa para aprender y creo que si un feature no le afecta en el funcionamiento o usabilidad a la solución pues manos a la obra. Este issue es un buen caso de estudio para mostrar como la aplicación se puede integrar y convivir con servicios de terceros y no le resta valor a la usabilidad. Si no es el momento de dedicarle el tiempo podemos pornerlo como un feature a futuro. (Mi Opinión)

**Comment by amhed** [comment]
Por que no poder hacer ambas? 

- Aprender a priorizar es valioso, tanto en la vida del developer como en la del profesional en general
- Si lo enfocamos como si fuese un producto final, aprenderemos a escribir software que tiene no solo función, sino forma estética
- Los absolutos también son malos. Yo estaba pensando en simplicidad visual. Quizás se puede implementar de una forma que se vea/use facilmente

Que apero son los foros :P

**Comment by Willjobs94** [comment]
+1

**Comment by luis-ramirez** [comment]
Working on this feature
