### ISSUE TITLE
Titulo más empleos de esta compañia

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#176]
Mejora para que si una compañía no posee mas empleos no aparezca la sección Más Empleos de esta Compañia
 
![empleado](https://cloud.githubusercontent.com/assets/3052715/12379028/618f6cea-bd27-11e5-8d5e-c51894544504.JPG)

**Comment by amhed** [comment]
:+1:

**Comment by luis-ramirez** [comment]
I take it!

**Comment by luis-ramirez** [comment]
Done in PR #182

**Comment by claudiosanchez** [comment]
Lo cerramos entonces?
