### ISSUE TITLE
CSS Cleanup

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#178]
- Bootstrap.css debería venir desde un paquete (browserify o nuget)
- Los archivos originales no deberían ser modificados
- El folder `/fonts` debería moverse dentro de `/Content`

**Comment by RaulMonteroC** [comment]
Yo agregaría cambiar a un preprocesador (preferiblemente LESS para evitar tener que instalar ruby) para poder mantener el código css mas segregado y limpio.

**Comment by christianrd** [comment]
Yo opino utilizar stylus ya que solo tienes que instalar nodejs y es muy facil de usar... :D
