### ISSUE TITLE
Javascript Cleanup

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#179]
- Separar paquetes que son de vendors (jQuery, underscore, validate, etc)
- Remover paquetes repetidos (modernizr aparece dos veces)
- Borrar archivos que no son usados: i18n es estándar, pero nosotros no tenemos la página localizada. Si se localiza un día lo incluimos

**Comment by jeanrodriguez** [comment]
i'll take this one

**Comment by RaulMonteroC** [comment]
@jeanrodriguez Como vas con este issue?

**Comment by jeanrodriguez** [comment]
Ootra persona lo puede tomar.
