### ISSUE TITLE
Refactoring: JobOpportunityController

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#181]
- JobOpportunityController solo debería interactuar con repositorios o con servicios
- De pueden mejorar algunos fragmentos (e.g. Linea 58, para la construcción de la variable `relatedJobs`) dentro de colaboradores que pueden ser probados/reemplazados por mocks
- El controlador deberías tener unit tests

**Comment by luis-ramirez** [comment]
#184
