### ISSUE TITLE
Cuando no se pone logo de la compañía, poner un placeholder.

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#185]

**Comment by claudiosanchez** [comment]
+1

**Comment by jgtaveras** [comment]
@claudio, colocamos el logo de emplea.do??

**Comment by claudiosanchez** [comment]
@jgtaveras Puede ser. Aunque nota que el logo de empleado actual es rectangular, y el espacio en la lista es más cuadrado.
Un ejemplo de placeholder debajo. 
https://www.royalacademy.org.uk/assets/placeholder-1e385d52942ef11d42405be4f7d0a30d.jpg
