### ISSUE TITLE
Implementar Inversion of Control (IoC)

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#196]
Para entonces hacer DI.

**Comment by claudiosanchez** [comment]
PelucheDI :)

Claudio Sanchez
240.361.7659
Claudio@megsoftconsulting.com
Megsoft Consulting Inc




On Fri, Jan 22, 2016 at 5:56 AM -0800, "Enmanuel Toribio" <notifications@github.com> wrote:












Para entonces hacer DI.

**Comment by EfrainReyes** [comment]
Ahora que el refactoring del proyecto está hecho, podemos proceder con este ticket. Lo tomaré.
