### ISSUE TITLE
Colocar fecha de publicación en el Detalle de la vacante.

### ISSUE THREAD

**Issue by gratereaux** [developersdo/empleo-dot-net#198]
En el listado de empleos se muestra la fecha de creacion de la vacante, pero luego al entrar al detail view de la vacante, la fecha no se presenta.
Seria bueno presentar la fecha de publicado porque cuando las personas entran directo o mediante un social link el usuario no se fija de cuando es la vacante.

Saludos

**Comment by luis-ramirez** [comment]
+1

**Comment by DannyFeliz** [comment]
+1

**Comment by jugomez** [comment]
+1

**Comment by claudiosanchez** [comment]
+1

**Comment by eatskolnikov** [comment]
https://github.com/developersdo/empleo-dot-net/pull/207
