### ISSUE TITLE
Error Logging - ELMAH

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#199]
- Agregar soporte para ELMAH (https://elmah.io), preferiblemente via un paquete de nuGet
- Configurar la ruta emplea.do/elmah
- Permitir acceso solo a usuarios administrativos

**Comment by jgtaveras** [comment]
@amhed  el acceso a los administradores sería cuando agreguemos la parte de autenticación, podemos implementarlo y dejar la ruta abierta, o esperar a que la parte de auth este in place

opiniones
@luis-ramirez @claudiosanchez @amhed @eatskolnikov @hminaya

**Comment by eatskolnikov** [comment]
Log4net is still free https://www.nuget.org/packages/log4net/

**Comment by amhed** [comment]
Log4Net allow us to log whenever we want. ELMAH deploys some handlers to capture errors that were unhandled by try/catch blocks and log them. 

http://stackoverflow.com/questions/5057674/what-is-the-difference-between-log4net-and-elmah

**Comment by amhed** [comment]
@jgtaveras podemos dejarlo abierto entonces, este proyecto es opens source, no importa que se vean los errores

**Comment by claudiosanchez** [comment]
In addition, my dear @eatskolnikov; Log4net's development has been stagnant for a while. NLog is highly adopted Logging framework.

**Comment by eatskolnikov** [comment]
@claudiosanchez thanks for the clarification. 
@amhed el issue con ELMAH es que hay que pagar, es cheap pero alguien tiene que entrar el número de la tarjeta y pagarlo y mantener la suscripción, lo que agrega un compromiso extra. Unless someone (you?) can get it for free or commits to pay for it, i find it pretty hard to keep it up for long ):

Apoyo la moción de usar NLog instead of ELMAH

**Comment by amhed** [comment]
No hay que pagar. Solo hay que bajar el nuget package bro: 
https://www.nuget.org/packages/elmah/

**Comment by amhed** [comment]
https://elmah.io es un servicio que alguien montó "on top of" elmah para dar un valor agregado

**Comment by eatskolnikov** [comment]
@amhed por eso eres un diox, yo solo había visto https://elmah.io/ :v bendito seax

**Comment by amhed** [comment]
Dejen de endiosar a la gente

**Comment by Willjobs94** [comment]
jejejeje ese @eatskolnikov y sus Xs

**Comment by eatskolnikov** [comment]
Hice una prueba con otro proyecto. Instalar ELMAH es literalmente agregar el nuget package... i'll take this one :eyes:
