### ISSUE TITLE
Agregar un logo default a los empleos que no tienen.

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/empleo-dot-net#200]
Debido a que no siempre es una empresa la que publica la vacante, es necesario agregar una imagen default para los que no tienen logo.

![2016-01-23 06_33_40-- emplea do](https://cloud.githubusercontent.com/assets/5460365/12529785/6319490a-c19b-11e5-8195-ff625a3f3052.png)

**Comment by jeanrodriguez** [comment]
Se prodria poner una imagen con la primera letra del nombre y el apellido, o solo la primero letra del nombre de la empresa. 
No se tiene que crear un imagen se puede poner solo la letra y darle estilo con css.

**Comment by jugomez** [comment]
+1

**Comment by luis-ramirez** [comment]
+1

**Comment by Willjobs94** [comment]
+1
