### ISSUE TITLE
Quitar el link de "Home"

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/empleo-dot-net#211]
Quitar el link de "Home". Como anteriormente se tenía un una página de inicio y se quitó pues este link no es necesario ya que "Lista de empleos" y "Home" van al mismo sitio.

![2016-01-27 00_12_46-listado de empleos - emplea do](https://cloud.githubusercontent.com/assets/5460365/12603627/c87426fc-c48a-11e5-9c3b-0e1a0457336f.png)

**Comment by Willjobs94** [comment]
Realmente no van al mismo sitio
![screenshot 2016-01-27 06 44 09](https://cloud.githubusercontent.com/assets/10265964/12611237/109bd0a6-c4c2-11e5-9301-af8c43e42a17.png)
![screenshot 2016-01-27 06 44 49](https://cloud.githubusercontent.com/assets/10265964/12611238/10c9e392-c4c2-11e5-8eda-b5a9c64de691.png)

**Comment by eatskolnikov** [comment]
@DannyFeliz El frontpage va de todas formas y se va a cambiar un poco en el futuro para que se note más la diferencia.
