### ISSUE TITLE
Mostrar customised page cuando no se encuentren datos para una busqueda

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#212]
Cuando se realiza una búsqueda y no se encuentran datos se debería mostrar un mensaje o página más descriptiva al usuario

![capture](https://cloud.githubusercontent.com/assets/3052715/12649621/c3d8d38c-c5b5-11e5-9b21-
e05b14ef2487.PNG)

**Comment by luis-ramirez** [comment]
no se ve el ejemplo :).
