### ISSUE TITLE
Mostrar cantidad de trabajos disponibles para una categoría.

### ISSUE THREAD

**Issue by anyeloamt** [developersdo/empleo-dot-net#213]
Sería algo parecido a esto:

![capture](https://cloud.githubusercontent.com/assets/2273293/12654904/a6581bee-c5cc-11e5-992a-8fcbda2d6643.PNG)

**Comment by jugomez** [comment]
Esto es seria cool para cuando se implemente el nuevo template.
+1

**Comment by sestalin1** [comment]
Donde estaría esa vista?

**Comment by RaulMonteroC** [comment]
Esto ya esta listo.
