### ISSUE TITLE
Friendly url cuando visualizas un empleo

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#218]
Al ver el detalle de un empleo. 

Que la url no se muestre como: www.emplea.do/detail/55

Mas bien algo asi: www.emplea.do/detail/55-front-end-developer

Esto ayuda con los index en los motores de búsqueda y más estético cuando se hace un share de url en los social media

![screen shot 2016-01-28 at 10 19 07 pm](https://cloud.githubusercontent.com/assets/3052715/12665401/ea2689d2-c60d-11e5-8591-fce60086a167.png)

**Comment by anyeloamt** [comment]
+1

**Comment by Willjobs94** [comment]
+1

**Comment by DannyFeliz** [comment]
+1

**Comment by RaulMonteroC** [comment]
+1

**Comment by AIsaac08** [comment]
+1

**Comment by AIsaac08** [comment]
+1
Podría ser algo como un slug y así nos desasemos del ID de la oferta, algo que haga más sentido por si alguien quiere compartir la URL pero no la copió y pegó, o whatever. puede ser incluso una combinación de la localización/tipo de trabajo con el título.
Ej: http://emplea.do/JobOpportunity/Remoto/Front-End-Developer

**Comment by frankelydiaz** [comment]
¿Qué tal si añadimos la fecha de publicación a la url también? 

Ej: http://emplea.do/JobOpportunity/Remoto/Front-End-Developer-2015-01-01

**Comment by luis-ramirez** [comment]
+1
-1 la fecha, no le veo la ventaja a simple vista

**Comment by frankelydiaz** [comment]
Si solo pones el título y tienes varias ofertas de Front-End-Developer tendrías que tener algo para distinguir una de la otra en la URL.

**Comment by jugomez** [comment]
@frankelydiaz puedes ir al PR #224. En este veras que se creo un Route para que el titulo en el URL no sea contemplado como parte de la ruta al hacer la llamada al controller

**Comment by frankelydiaz** [comment]
Ah, nítido, no había visto el PR. La solución que le dieron me parece mucho mejor que lo de la fecha que mencione.
