### ISSUE TITLE
Deshabilitar la ubicación de remoto

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#219]
Que la ubicación (Remoto) no esté disponible para seleccionar cuando se está creando un empleo. Para esto se creó el campo específico

![screen shot 2016-01-28 at 10 44 59 pm copy](https://cloud.githubusercontent.com/assets/3052715/12665891/a4f2351a-c611-11e5-925b-ef9f6ca67170.png)

**Comment by eatskolnikov** [comment]
No estoy de acuerdo, la empresa tiene una localidad física.

**Comment by jugomez** [comment]
@eatskolnikov Te puedes explicar un poco mejor?

**Comment by anyeloamt** [comment]
Me imagino que @eatskolnikov se refiere a que la empresa está establecida en una localidad, aunque el empleo sea remoto se debería proporcionar la ubicación de la empresa.

Aunque eso da cabida a confusiones, una persona que anda buscando empleo en el site puede pensar que aunque el empleo sea remoto este debe vivir en la localidad de la empresa.

**Comment by jugomez** [comment]
Pues entonces no hace sentido tener un field adicional para indicar que un trabajo es remoto.

**Comment by luis-ramirez** [comment]
a ver hace sentido, lo unico que habria es que hacer un update en la DB y cambiar a NA

**Comment by jugomez** [comment]
@luis-ramirez Esa puede ser una opción!. Creo que se debió hacer eso que indicas cuando se hizo el PR para el ISSUE #159

**Comment by claudiosanchez** [comment]
Mmm; correcto. Ese Location = Remote es un vestigio de los tiempos cuando no teniamos el Checkmark para "Remoto". 

¿Quien se anima? No PR Required. @luis-ramirez Ve y juega en producción mijo.

**Comment by luis-ramirez** [comment]
Done!
