### ISSUE TITLE
Cambiar el formato de fecha en los display

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#220]
Como usuario me gustaría ver las fechas en un formato más legible.

![screen shot 2016-01-28 at 10 44 59 pm](https://cloud.githubusercontent.com/assets/3052715/12665942/3b8d1d1e-c612-11e5-8352-f176f765da53.png)

**Comment by anyeloamt** [comment]
+1

**Comment by RaulMonteroC** [comment]
+1

**Comment by jugomez** [comment]
Este ISSUE hay que volverlo a abrir. El cambio solo se realizo en la pagina principal.

Cuando vas a la http://www.emplea.do/JobOpportunity el formato no fue aplicado hay.

**Comment by eatskolnikov** [comment]
@jugomez ahí mismo atiende el #222 y crea un partial view para esa tabla
