### ISSUE TITLE
Navegación proceso guíado de creación de posiciones

### ISSUE THREAD

**Issue by jgtaveras** [developersdo/empleo-dot-net#228]
El proceso guíado de creación de posiciones permite navegar entre las secciones si se hace click sobre los botones guias en el fondo del wizzard

![screen shot 2016-02-05 at 10 47 48 am](https://cloud.githubusercontent.com/assets/1023322/12849432/fa3476fc-cbf5-11e5-95f2-3f49cd7dbe5c.png)
![screen shot 2016-02-05 at 10 48 06 am](https://cloud.githubusercontent.com/assets/1023322/12849431/fa33aa42-cbf5-11e5-8646-23aaf28d67e8.png)

Adicionalmente considero lo siguiente:

El link para que el usuario utiliza el wizzard debe ser mas visible o con unos colores mas destacados
Los pasos o secciones que contemplan el wizzard debe ser visibles al usuario es decir:
Detalle de la empresa  ---  Detalle del puesto --- La prueba de joel -- Resumen del post

**Comment by jugomez** [comment]
En adición: Si el usuario esta por ejemplo en el steep la prueba de joel y cuando hace clic en Crear Empleo y existe algún error en la validación del formulario se debe mostrar alguna alerta de que los campos están invalidos.

Actualmente si uno intenta hacer clic en Crear Empleo y existen errores de validación da la sensación de que el sistema no responde o tiene un bug.

**Comment by RaulMonteroC** [comment]
Yo me encargo de esto.

**Comment by RaulMonteroC** [comment]
@jugomez No logro entender el error que describes. Me explicas ?

**Comment by jugomez** [comment]
@RaulMonteroC según veo en producción hicieron una mejora. Antes hacías clic en siguiente y no validaba los campos requeridos antes de pasar a la siguiente.

Pero aun persiste una deficiencia. Si usas los botones de navegación que están al pie del wizard. Y vas directamente al ultimo paso y das clic en crear empleo. Todo esto dejando campos requeridos vacíos. Veras que das clic y no aparece un mensaje o validation summary indicándote que no puedes guardar porque el formulario no esta valido.

**Comment by RaulMonteroC** [comment]
Perfecto. Gracias por la aclaración.

**Comment by jgtaveras** [comment]
@luis-ramirez este issue no esta cerrado
