### ISSUE TITLE
Acceso a la DB para dar mantenimiento a contenido

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#230]
Crear un usuario con permisos data write para dar mantenimiento al contenido.

Ejemplo cuando alguien publica un empleo basura poder eliminarlo @claudiosanchez

**Comment by luis-ramirez** [comment]
#235

**Comment by RaulMonteroC** [comment]
En que quedo esto? Se hará en algún momento?

**Comment by Willjobs94** [comment]
@RaulMonteroC como dice @luis-ramirez, este issue se resuelve con el #235 así que considero que podemos cerrarlo.

**Comment by RaulMonteroC** [comment]
De acuerdo contigo. Cerrando este issue. Lo relacionado a esto se tratara en el #235
