### ISSUE TITLE
Backend App

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#235]
Esto es un poco grande pero creo que nos ayudaría bastante y es tener un app **Backend (MVC)** en donde se puedan hacer tareas de mantenimiento como:

- Crear nuevas localidades
- Eliminar post basura
- Aprobar los trabajos
- Poder actualizar un post

Claro, dicha app tendría que tener authentication para los admins y así se evita estar jugando en producción :)

Solo habría que:

- Crear el proyecto MVC
- Agregar las referencias al core 
- Métodos necesarios para cada acción en la capa de servicio 
- Authentication con Identity (terminar de configurar)

**Comment by DannyFeliz** [comment]
+1

**Comment by RaulMonteroC** [comment]
Yo estoy de acuerdo con esto. Ahora, creo que seria prudente que se realizen primero los issues concernientes al cambio de UI y la implementación via identity para no tener que trabajar dos veces.

**Comment by eatskolnikov** [comment]
@RaulMonteroC  +1
También creo que sería mejor partir esto y crear un feature a la vez, así se le da oportunidad a mas personas de participar en esto. Lo primero primero es hacer lo del identity, luego es crear el proyecto nuevo y hacer el push, al final poner un issue por crud

**Comment by Willjobs94** [comment]
@RaulMonteroC  creo que ya se puede trabajar con este issue, cierto ?

**Comment by RaulMonteroC** [comment]
Casi. Falta algo importante y es que se puedan crear roles de usuario. Actualmente solo inician sesión las empresas pero debemos hacer lo mismo para los candidatos y (para este request) los admins. Entiendo que tan pronto hagamos eso se podria hacer esta parte.

Tambien cabe destacar que aquí esta toda la app como un single feature. Yo creo que cuando se comience a trabajar deberiamos de hacer un hangout para definir todo lo que va, crear un nuevo label y añadirselo a los issues detallados que salgan de ahí. De esta forma varias personas pueden aportar.
