### ISSUE TITLE
Evitar desplazamiento a la siguiente ventana

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/empleo-dot-net#237]
En el nuevo [proceso guíado de creación de posiciones ](http://emplea.do/JobOpportunity/Wizard) evitar que se desplace al siguiente/anterior paso si el drag se hace dentro de input ya que es algo incómodo si por ejemplo ya he escrito algo y quiero seleccionarlo con el mouse no puedo. En el único sitio en el que esto no sucede es en el textarea de "Requisitos para aplicar"

![2016-02-08 23_00_13-nuevo empleo-emplea do](https://cloud.githubusercontent.com/assets/5460365/12906559/e7973704-ceb7-11e5-95c5-58f0f4e9607b.png)

**Comment by luis-ramirez** [comment]
Este issue existe y esta siendo trabajado por @RaulMonteroC #228
