### ISSUE TITLE
Agrega un certificado de seguridad

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#239]
Como vamos a lidiar con identity ya se hace necesario, aquí hay dos sites donde dicen que regalan certificados
https://www.startssl.com/
https://letsencrypt.org/

**Comment by RaulMonteroC** [comment]
@eatskolnikov Has usado alguna de estas opciónes? en caso de que si, que tal te ha ido?

**Comment by eatskolnikov** [comment]
@RaulMonteroC he usado ambas pero ninguna con azure, la versión de letsencrypt es super fácil de instalar
