### ISSUE TITLE
Permitir a los que postean trabajos especificar que ya no van a recibir más cv's

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#245]
Un checkbox que diga algo como "No recibiremos mas candidatos para esta posición" y que en el detalle del anuncio en vez del correo salga "Esta posición no recibe más candidatos" y un alert-danger arriba que diga "Esta posición no recibe más candidatos"

**Comment by RaulMonteroC** [comment]
Muy buena la idea. Creo que para esto hay que esperar que los trabajos puedan editarse ya que poner esta opción cuando un trabajo recien se crea no hace mucho sentido.

**Comment by RaulMonteroC** [comment]
Creo que esto se puede hacer más interesante haciendo que las empresas puedan desactivar empleos para que no aparezcan en el listado.

**Comment by Willjobs94** [comment]
Creo que con el #435 se resuelve esto.

**Comment by RaulMonteroC** [comment]
@Willjobs94 es parecido, pero no es lo mismo. Cuando lo deshabilitas lo que haces es que no se muestre en el listado de empleos pero el usuario que lo creo tiene acceso ese JobOpportunity y puede habilitarlo en cualquier otro momento. En el caso de eliminar cuando se elimina se pierde el acceso y solo lo puede recuperar un admin.

Al menos así es como lo veo.

**Comment by Willjobs94** [comment]
Can someone assign this to me, please ?
