### ISSUE TITLE
Manejar trabajo no encontrado

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#250]
Si uno visita una posicion que no existe ( [Ejemplo](http://emplea.do/JobOpportunity/Detail/1) ) la pagina da un error 500.

Intentar acceder a una posicion no existente deberia generar un error 404 y no un error 500.

**Comment by codnee** [comment]
@luis-ramirez Close the issue.

**Comment by luis-ramirez** [comment]
Esto no está listo aún

**Comment by RaulMonteroC** [comment]
ohh my bad. Pense que ya se había terminado.
