### ISSUE TITLE
Evitar viajes innecesarios a la base de datos

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#251]
Si los valores que se les pasan a los repositorios no son validos (ej: un Id <= 0 ) el viaje a la base de datos deberia evitarse completamente para evitar ese overhead.

**Comment by luis-ramirez** [comment]
Podrias dar ejemplos en el codigo?

**Comment by codnee** [comment]
En JobOpportunityRepository
```csharp
        public JobOpportunity GetJobOpportunityById(int? id)
        {
            if (!id.HasValue) return null;
            return DbSet.Include(x => x.Location).Include(x=>x.JoelTest).FirstOrDefault(x => x.Id.Equals(id.Value));
        }
```

Se esta confimando que el id tiene valor, pero no que el valor es aceptable (id > 0).

**Comment by luis-ramirez** [comment]
como podria llegar un 0 a esa linea?

**Comment by jgtaveras** [comment]
@codnee en este caso el único valor inadmisible es el 0, el cual sólo llegaría al controller si el usuario deliberadamente lo coloca, estoy es un corner case muy especifico que no creo valga la pena evaluar, si tienes otros por favor

**Comment by codnee** [comment]
En ese caso, no se deberia quitar el if statement completamente?

Como llegaria un null ahi? Y si no se acepta null por que es un nullable parameter?
