### ISSUE TITLE
El JobOpportunity search funciona de manera inadecuada.

### ISSUE THREAD

**Issue by erickconcepcion** [developersdo/empleo-dot-net#255]
**El JobOpportunity necesita arreglos.**
Como se muestra en la 2da imagen el index de JobOpportunity muestra todos las oportunidades de empleos como debe ser. Pero, dicho caso se presenta también en la imagen 1 a pesar de que (por asunción propia) el JobCategory mostrado en dicha imagen no existe, mas los resultados de su búsqueda son todos los elementos.

Lo apropiado seria lo que pasa en la ultima imagen, que si buscamos en base a solo caracteres numéricos no aparece ningún elemento. Ya que fuera de eso segun la 3ra imagen, la búsqueda funciona a la perfección.

**Adelante y Suerte con eso**
![all](https://cloud.githubusercontent.com/assets/17211878/13026262/bc153660-d1f7-11e5-9edd-01c8f70240c6.png)
![index](https://cloud.githubusercontent.com/assets/17211878/13026263/bc1f8e80-d1f7-11e5-96e4-d46277afcbc9.png)
![result](https://cloud.githubusercontent.com/assets/17211878/13026265/bcadc1fa-d1f7-11e5-8148-1b0c6553bc35.png)
![zero](https://cloud.githubusercontent.com/assets/17211878/13026264/bc34f2de-d1f7-11e5-81f7-c432262a521f.png)

**Comment by eatskolnikov** [comment]
Esto no es necesariamente un problema, es un edge case muy específico que no rompe nada. Intenta responder estás dos preguntas ¿Por qué un usuario común habría de navegar el sitio cambiando la url directamente? y ¿Esto daña la experiencia del usuario de alguna manera?

**Comment by erickconcepcion** [comment]
gracias man, buscare otro issue de mayor relevancia, aun asi dejare este abierto por si a alguno o en su debido momento a mi nos apetece realizarlo

**Comment by jugomez** [comment]
@erickconcepcion este issue se debatió en slack. Será trabajado en su momento y se determinó que tiene su valor. Good Job :+1:
