### ISSUE TITLE
Estadisticas del Sitio

### ISSUE THREAD

**Issue by jgtaveras** [developersdo/empleo-dot-net#257]
Sería interesante si agregaramos una sección donde se publiquen estadisticas del sitio como:
- Cantidad de puestos publicados
- Cantidad de visistas
- Puesto mas visitado
- Usuarios del site (cuando este listo)

**Comment by RaulMonteroC** [comment]
Esto es algo interesante para colocar en la pantalla de inicio del nuevo template como una manera de vender el sitio. +1

**Comment by eliezerpujols** [comment]
Wow +1 @jgtaveras

**Comment by luis-ramirez** [comment]
Voy a esto 
<img width="1425" alt="screen shot 2016-05-08 at 11 53 26 am" src="https://cloud.githubusercontent.com/assets/6517152/15098796/85c9d188-1513-11e6-9877-04233224c225.png">
