### ISSUE TITLE
Fix some unformatted text 

### ISSUE THREAD

**Issue by Willjobs94** [developersdo/empleo-dot-net#259]
![screenshot 2016-02-16 00 20 48](https://cloud.githubusercontent.com/assets/10265964/13067148/9e0824fe-d443-11e5-80cc-875da814c2a5.png)

 
Some text are ugly formatted

**Comment by eatskolnikov** [comment]
This is pretty odd. El charset está en UTF-8. ¿Qué será? =/

**Comment by erickconcepcion** [comment]
this is so strange, cause before the text format was working ok

**Comment by erickconcepcion** [comment]
To highlight the data area of the rendered view has no problems, like you can see.
![2016-02-16](https://cloud.githubusercontent.com/assets/17211878/13094940/6c725788-d4e4-11e5-8415-6dd774d05e88.png)

**Comment by Willjobs94** [comment]
In my case, shows the code, the same as the page.
![screenshot 2016-02-18 19 10 37](https://cloud.githubusercontent.com/assets/10265964/13161353/8ad9fe3e-d673-11e5-8a51-2bf8d79f7676.png)

I guess could be a configuration on the server, 'cause locally it works fine

**Comment by erickconcepcion** [comment]
it must be

**Comment by RaulMonteroC** [comment]
All english. +1 everybody. :smile:

**Comment by dhemmat** [comment]
solved: https://github.com/developersdo/empleo-dot-net/pull/277
