### ISSUE TITLE
Ver post de los empleos

### ISSUE THREAD

**Issue by gromney** [developersdo/empleo-dot-net#261]
Cómo seguidor de Emplea.do en Facebook y Twitter quisiera que se auto posteen los empleos. Estilo we work remotely.

**Comment by luis-ramirez** [comment]
Actualmente los trabajos se están mostrando en twitter vía emplea_do

**Comment by gromney** [comment]
Yo no veo ningún tweet

**Comment by luis-ramirez** [comment]
<img width="1440" alt="screen shot 2016-02-17 at 8 47 00 am" src="https://cloud.githubusercontent.com/assets/6517152/13109882/841b1bf4-d552-11e5-8a79-46646977c43b.png">
