### ISSUE TITLE
Cambiar el esquema de las urls

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#263]
Ahora mismo las Urls no son tan friendly. Propongo los siguientes cambios:

- http://emplea.do/JobOpportunity => http://emplea.do/jobs
- http://emplea.do/JobOpportunity/New => http://emplea.do/job/new
- http://emplea.do/JobOpportunity/Wizard => http://emplea.do/job/wizard
- http://emplea.do/JobOpportunity/Detail/79-Desarrollador-IOS =>http://emplea.do/job/79-Desarrollador-IOS.

Las urls viejas seguirian funcionando pero se comenzarian a usar estas nuevas por defecto. Esto se puede hacer agreando algunas configuraciones al RouteConfig.

**Comment by EfrainReyes** [comment]
yo las pondria "jobs" en minuscula pero eso soy yo

**Comment by RaulMonteroC** [comment]
Good point. Las Urls por lo general las he visto así. Deja actualizar.

**Comment by EfrainReyes** [comment]
http://stackoverflow.com/a/11647303/2563028 para referencia

**Comment by codnee** [comment]
Y ese mangú en el root? Deberias hacer todas las demas urls child de jobs.

- http://emplea.do/JobOpportunity => http://emplea.do/jobs
- http://emplea.do/JobOpportunity/New => http://emplea.do/jobs/new
- http://emplea.do/JobOpportunity/Wizard => http://emplea.do/jobs/wizard
- http://emplea.do/JobOpportunity/Detail/79-Desarrollador-IOS =>http://emplea.do/jobs/79-Desarrollador-IOS.

**Comment by RaulMonteroC** [comment]
Recueda que es a nivel de visualización solamente. No puse Jobs porque hasta ahora nadamas esta utilizandose esa entidad (en la Urls). Es como decir la entidad por defecto.

**Comment by codnee** [comment]
Simplemente me parece que mantener integridad semantica en las url desde el principio es una buena idea.

**Comment by EfrainReyes** [comment]
+1 @codnee, /jobs/new tiene mas sentido

**Comment by claudiosanchez** [comment]
+1 @codnee /job/*

**Comment by luis-ramirez** [comment]
+1 @codnee

**Comment by RaulMonteroC** [comment]
Nice. Pues así se coloca. Lo actualizare en el header

**Comment by luis-ramirez** [comment]
cual header?
porque arriba dice job para new, wizzard y details

**Comment by RaulMonteroC** [comment]
Ahí mismo. Justo ahora lo actualice

**Comment by luis-ramirez** [comment]
pero porque los trabajos jobs y si es a crear un nuevo trabajo dice job?

**Comment by codnee** [comment]
Semantica. Jobs es trabajos, job es trabajo. Cuando entras a /**jobs** ves los **trabajos**, cuando entras /**job**/_new_ estas creando un _nuevo_ **trabajo.**

**Comment by luis-ramirez** [comment]
Es que lo veo extrańo, al final son trabajos y creas un trabajo dentro de los trabajos, por ejemplo mira como es stack-overflow careers

**Nuevo trabajo**
<img width="1440" alt="screen shot 2016-02-18 at 7 26 55 pm" src="https://cloud.githubusercontent.com/assets/6517152/13161590/206ff4c0-d675-11e5-83e8-38dbacd08cd1.png">

**Lista de trabajos**
<img width="1440" alt="screen shot 2016-02-18 at 7 27 14 pm" src="https://cloud.githubusercontent.com/assets/6517152/13161591/20778ece-d675-11e5-8d79-04c82ccf9b2f.png">

**Comment by codnee** [comment]
+1 jobs/* para todo.

Me gusta la consistencia.
