### ISSUE TITLE
Remover las categorías "invalid" y "todas" del listado de categorías en el dropdown

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#272]
![screen shot 2016-02-23 at 11 05 58 am](https://cloud.githubusercontent.com/assets/1693000/13255686/8de64814-da1d-11e5-9c15-12ad6fce9a9a.png)

**Comment by luis-ramirez** [comment]
No se pueden remover Todas porque sino alteraremos el comportamiento del search

**Comment by RaulMonteroC** [comment]
Por lo menos para la parte de creación de trabajos hace sentido que no esten ni invalid ni todas

**Comment by ncarrasco** [comment]
@RaulMonteroC  Si quisiera publicar un new job y seleccionar todas las categorías porque por alguna razón considero que debe ser así, para mí sería más fácil seleccionar “Todas” que una x una.
por esa razón creo que “Todas” debe de ir, además como dice @luis-ramirez, afectaría el comportamiento del search.

Simple Opicion.. :+1:

**Comment by eatskolnikov** [comment]
@ncarrasco El problema con "Todas" es que es muy probable que no encuentres lo que buscas si tu búsqueda es muy broad.

**Comment by RaulMonteroC** [comment]
@ncarrasco Dos cosas.

- En primer lugar,  dificilmente vamos a tener un JobOpportunity que necesite tener todas las categorias. Actualmente tenemos unas cuantas y puede que se expandan y se vuelvan más diversas.
  * Diseño Gráfico
  * Desarrollo Web
  * Desarrollo para Moviles
  * Desarrollo de Software
  * Administrador de sistemas
  * Redes y telecomunicaciones
  * IT Ventas
  * Administrador de base de datos

- En Segundo lugar, lo que propones entiendo que se podria soportar si pudieramos seleccionar multiples categorias para un empleo y utilizar la opción "todas" en caso de que el usuario no quiera filtrar las categorias. Esto es algo que al día de hoy no es tan importante pero que pudiera serlo a medida que el sistema crece.

**Comment by RaulMonteroC** [comment]
Una pregunta. La razón de ser de la categoria invalid cuál es?

**Comment by luis-ramirez** [comment]
@eatskolnikov te llama @RaulMonteroC

**Comment by eatskolnikov** [comment]
@RaulMonteroC Atendiendo el #255 y para que cuando se haga una búsqueda por categoría y la categoría no sea válida el enum tome ese valor por defecto. Así no se muestra ningún resultado cuando buscas por una categoría errónea.

**Comment by RaulMonteroC** [comment]
Ya entiendo. Good.

**Comment by claudiosanchez** [comment]
- El Enum para categorías no debe estar influenciado por la búsqueda. 
- Un trabajo que necesita seleccionar "todas" no es un trabajo válido; a menos que quieran un Bugs Bunny, y ese es un trabajo de baja calidad que no tiene lugar en esta plataforma de trabajos. 
- ¿Para que el "      " que sale como primera opción?

**Comment by ncarrasco** [comment]
y esta **vainilla** está open?...
Se ve facil, puedo empezar por aquí!.. :1234:

**Comment by Willjobs94** [comment]
@RaulMonteroC, @claudiosanchez, @eatskolnikov 
El problema con eso ahora, es que solo se puede arreglar en el html, porque si se elimina alguna categoría del enum, para poder segur usando `Html.EnumDropListFor` method, entonces si algún trabajo tiene ya esa categoría va a dar un error mostrando dicha categoría.

Entonces la pregunta es si, aceptarían un PR que simplemente lo arregle en el html?
O si vamos a hacer un mantenimiento de la base de datos  para determinar todos los que tienen las categorías "todas" e "invalid" y actualizar el campo a uno válido ?

**Comment by claudiosanchez** [comment]
Esto debe incluir una migración de Data quality que mueva cualquier trabajo anteriormente asignado a estas categorías invalidas a una que sea valida.

**Comment by RaulMonteroC** [comment]
De acuerdo con lo que menciona @claudiosanchez. Luego de hacer el PR se tendria que hacer un update de la base de datos para que todo siga funcionando adecuadamente luego del cambio.

Para este caso creo que seria prudente que el que se encargue de hacer este PR incluya el script de base de datos que se utilizara para hacer la actualización, de esta manera tambien podemos hacer pruebas antes de hacer el cambio y no dejarlo todo para el final.
