### ISSUE TITLE
Definir tamaño máximo para la imagen de la compañia

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#283]
Definir un tamaño máximo en la imagen que se muestra en la sección de compañías para mantener un aspecto que no ropa el layout de la pagina.

 
![capture](https://cloud.githubusercontent.com/assets/3052715/13364947/8a7b2432-dca8-11e5-857d-a3ea31dbb855.PNG)

**Comment by luis-ramirez** [comment]
Mas bien el Height?

**Comment by anyeloamt** [comment]
We have to close this issue.
