### ISSUE TITLE
New template link

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#286]
Crear un mensaje en el **Index** del **HomeController** que de acceso al usuario de que accese al nuevo template

**Comment by eatskolnikov** [comment]
¿Cuál es la url del nuevo template? pregunto porque recuerdo que mandaron está primero https://empleado-template.azurewebsites.net/ y luego mandaron otra en el slak

**Comment by RaulMonteroC** [comment]
@eatskolnikov  http://beta-empleado.azurewebsites.net/

**Comment by Willjobs94** [comment]
The first one, was only the hmtl, but the second one is the implementation of the new template design in a working copy of emplea.do
