### ISSUE TITLE
Usar .ConfigureAwait(false) en métodos que usen async/await

### ISSUE THREAD

**Issue by EfrainReyes** [developersdo/empleo-dot-net#288]
En ASP.NET, si no usas ConfigureAwait(false) eso puede terminar en deadlocks cuando uno trate de esperar el resultado de la llamada async.

Aquí se explica bien: http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

El código donde esto ocurre en cuestión es el action `JobOpportunityController > New`, donde se hace una llamada async para postear un tweet.

**Comment by codnee** [comment]
Si el task esta siendo awaited (usando await) antes de continuar la ejecución, como es el caso en el action que mencionaste, no hay un deadlock.
