### ISSUE TITLE
Aveces no es necesario mandar el CV

### ISSUE THREAD

**Issue by delgiudices** [developersdo/empleo-dot-net#293]
En algunos casos, donde yo trabajo por ejemplo. No manejamos a los aplicantes a traves de correos, sino que los redireccionamos a una pagina donde pueden aplicar.

**Comment by luis-ramirez** [comment]
+1

**Comment by RaulMonteroC** [comment]
+1

**Comment by EfrainReyes** [comment]
+1

**Comment by Edulopez** [comment]
+1

**Comment by ltavarez** [comment]
Creo que se podria poner un select para elegir la forma de aplicar si es por cv o por un link al website, si elige mail pues se maneja como se hace actualmente y si es por link pues seria guardar el link en vez del mail y validar en el detalle del empleo como es que se va aplicar (habria que agregar un campo nuevo para manejar los link de los website cuando sea necesario).

**Comment by RaulMonteroC** [comment]
Yo lo haría más sencillo. En vez de tener un campo de correo para que se envien los curriculums ahí, podriamos tener un campo de texto que se llame how to apply y ya cada quien explique el proceso como entienda. Así si hay más opciones pues ya lo tenemos cubierto.

**Comment by ltavarez** [comment]
si pongo solo un how to apply como sabria si es un cv o un enlace?

tambien en ese caso habria que ver como se maneja en el detalle la parte que dice como aplicar, porque ahora mismo dice Enviar CV a [email] , seria bueno que cuando sea link diga aplicar en este enlace en vez de enviar cv , se podria usar el mismo text generico para los dos y poner dos radio para saber si es por cv o por enlace

**Comment by RaulMonteroC** [comment]
A lo que me referia era poner un text area y el usuario coloque ahi algo como: Envianos tu cv fulano@compania.com con el titulo tal o favor crearse una cuenta y llenar el formulario de nuestra pagina web www.compania.com.do.

La idea es dejar abierto al usuario para que decida como hacerlo en vez de poner un texto predeterminado. De esta manera damos más opciones.

**Comment by RaulMonteroC** [comment]
A lo que me referia era poner un text area y el usuario coloque ahi algo como: Envianos tu cv fulano@compania.com con el titulo tal o favor crearse una cuenta y llenar el formulario de nuestra pagina web www.compania.com.do.

La idea es dejar abierto al usuario para que decida como hacerlo en vez de poner un texto predeterminado. De esta manera damos más opciones.

**Comment by RaulMonteroC** [comment]
A lo que me referia era poner un text area y el usuario coloque ahi algo como: Envianos tu cv fulano@compania.com con el titulo tal o favor crearse una cuenta y llenar el formulario de nuestra pagina web www.compania.com.do.

La idea es dejar abierto al usuario para que decida como hacerlo en vez de poner un texto predeterminado. De esta manera damos más opciones.

**Comment by EfrainReyes** [comment]
+1 a lo que dice @RaulMonteroC, dejarle abierto al reclutador cómo desea que el candidato aplique. No podemos asumir que un link y un correo son las únicas formas de aplicar a un trabajo, puede que por ejemplo alguna empresa esté organizando una feria de empleos y quiere que la gente vaya presencial.
