### ISSUE TITLE
Título y Localidad deberían ser full width blocks.

### ISSUE THREAD

**Issue by gotjosh** [developersdo/empleo-dot-net#295]
Actualmente veo que `titulo` y `localidad` en la descripción de un empleo son `<span>` dentro de un `<h4>`, creo que deberían ser full width block element (such as `<h4>`?) para que no pase lo siguiente: 

![image](https://cloud.githubusercontent.com/assets/231583/13529621/984a3094-e1f3-11e5-9fe2-e35e4163cc1d.png)

**Comment by eatskolnikov** [comment]
@gotjosh Ya @luis-ramirez está atendiendo esto, haciendo que salgan en una linea cada uno. En una nota relacionada ahora mismo hay un issue de rehacer el template de la plataforma si sabes de UI te recomiendo que chequees este repo https://github.com/eatskolnikov/empleado-template/tree/develop y chequees como va quedando aquí http://beta-empleado.azurewebsites.net/

**Comment by gotjosh** [comment]
Hola @eatskolnikov ya ví que @luis-ramirez realizo el cambio en #292.
