### ISSUE TITLE
Markdown support para el body de la oferta

### ISSUE THREAD

**Issue by gotjosh** [developersdo/empleo-dot-net#296]
Creo que sería interesante tener markdown support para el body de la oferta, en mi caso casi siempre escribo todo utilizando algún tipo de Markdown editor y sería conveniente solo hacer copy paste.

**Comment by RaulMonteroC** [comment]
Esto ya se habia discutido en el issue #124

**Comment by gotjosh** [comment]
Gracias @RaulMonteroC. Cierro este y escribiré en el que ya estaba abierto.

PD: Hice una búsqueda de PR abiertos con el keyword markdown antes de ponerlo, pero no tome en cuenta los cerrados.
