### ISSUE TITLE
Como usuario quiero poder hacer login con Linkedin

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#302]
because professional and stuff

**Comment by RaulMonteroC** [comment]
+1 a esta opción.

**Comment by AIsaac08** [comment]
But why? Professional and stuff it's not a good reason for a feature, imho.

**Comment by eatskolnikov** [comment]
@AIsaac08 Es mas probable que las empresas tengan linkedin fuera del firewall y de verdad puedan loggearse.

**Comment by AIsaac08** [comment]
@eatskolnikov tu ve' esa si es una razón más coherente :p
+1

**Comment by delgiudices** [comment]
No sense to me

**Comment by eatskolnikov** [comment]
@delgiudices para ti no, pero esto es para la gente de Recursos Humanos
