### ISSUE TITLE
Filtrar posts por puntaje (upvote & downvote)

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#308]
Hacer que la comunidad pueda limpiar los jobs. Si la gente puede dar un "downvote" podríamos hacer algo para que después de cierto threshold este sea eliminado o pasado a otra categoría. Esto es algo parecido a lo que hace 9gag y el filtro de posts.

Este issue es resultado de la discusión realizada en el issue #162 y sugerida por @Edulopez

**Comment by Willjobs94** [comment]
+1
And I guess only registered (logged-in) user can makes downvotes and upvotes

**Comment by anyeloamt** [comment]
Lo podemos manejar con cookies, como se manejan las views de los empleos.

No he podido sacar tiempo para hacerlo, hoy continuaré con el.

**Comment by anyeloamt** [comment]
Can we close this issue now?

**Comment by RaulMonteroC** [comment]
Tan pronto se le haga merge al PR que los ordena por este campo.
