### ISSUE TITLE
La aplicación móvil debiera ser Xamarin.Forms

### ISSUE THREAD

**Issue by davidtavarez** [developersdo/empleo-dot-net#316]
Entiendo que la aplicación móvil debiera estar en Xamarin.Forms (PCL) como dice en el readme :+1:

**Comment by claudiosanchez** [comment]
@davidtavarez El readme está desactualizado. He creado el issue #317 para que se actualice el readme file con la visión actual del proyecto. 

Se decidió no usar Xamarin Forms para los proyectos móviles.

**Comment by davidtavarez** [comment]
@claudiosanchez ¿Alguna razón en específico? Ando como que desconectado :cry:

**Comment by claudiosanchez** [comment]
@davidtavarez El team tomó la esa opción de hacerlo nativo con Xamarin Android por la flexibilidad de explotar los features nativos, UX-wise de la plataforma. 

Este tipo de conversaciones dan lugar en el slack del proyecto, http://empleado.slack.com
