### ISSUE TITLE
Actualizar el Readme.md

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#317]
El Readme file del proyecto está desactualizado. 

Necesita: 
* Actualizar el Roadmap
* Refrescar la referencia tecnologías que se están utilizando actualmente.

**Comment by Willjobs94** [comment]
Should we update on english ?

**Comment by Edulopez** [comment]
Why not both?

No hay orgullo de ser bilingue?

**Comment by Willjobs94** [comment]
No es orgullo, pero eso permitiría que mas personas aportaran, aparte de que el ingles es como el estandar en los Readme de proyectos internacionales.

**Comment by eatskolnikov** [comment]
@Willjobs94  y @Edulopez el Readme principal en inglish y se puede hacer otro en español. @Willjobs94 crea el readme en ingles con los nuevos parametros y @Edulopez crea el que va en español y llamalo Readme.es.md

**Comment by Willjobs94** [comment]
We can close this Issue thanks to PR #347

**Comment by eatskolnikov** [comment]
@Willjobs94 It's not over yet

**Comment by eatskolnikov** [comment]
From now on all "notes" and stuff shall be added to the [wiki](https://github.com/developersdo/empleo-dot-net/wiki) let's make an effort to have the best wiki ever seen on the hub of gits :v
