### ISSUE TITLE
Abstract the access to appsettings

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#327]
To avoid using asp.net appsettings keys directly in the configuration phase and allow for some implementations to be made with database values or others.

**Comment by Edulopez** [comment]
You mean like creating a class that contains properties with the appsettings values?

**Comment by eatskolnikov** [comment]
No, algo como tener un "AppSettingsProvider" con un método Get, que retorne la propiedad
```C#
interface IProvideAppSettings{
 string Get(string name); 
} 
```
```C#
public class AppSettingsProvider : IProvideAppSettings{
 public string Get(string name){
 //Busco el setting desde la base de datos o desde un appsettings o una propiedad del mismo objeto or something
 }
}
```
y entonces llamo a:
```C#
appSettingsProvider.Get("fbAppSecret");
```

**Comment by anyeloamt** [comment]
¿Hay alguien en esto?

**Comment by eatskolnikov** [comment]
@anyeloamt no, todavía.
