### ISSUE TITLE
Crear página con ejemplo de oferta de trabajo.

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#330]
Como una manera de promover trabajos escritos de manera adecuada e incluyan toda la información que necesitan, sería bueno poder crear una pantalla muestre un ejemplo de una oferta de empleo bien estructurada e incluir un link hacia esta página en la pantalla de creación de ofertas de trabajo.

**Comment by Edulopez** [comment]
+1

**Comment by Willjobs94** [comment]
+1
It could be a bootstrap model that show up when the user click a button or link, showing the job opportunity example.
