### ISSUE TITLE
Implement the categories feature layout in the Mobile project

### ISSUE THREAD

**Issue by LuisAlbertoPenaNunez** [developersdo/empleo-dot-net#335]
Implement the categories feature layout as specified [in this document](https://goo.gl/QN9XfB)

**Comment by Willjobs94** [comment]
I recommend to add some image of how those it looks

**Comment by LuisAlbertoPenaNunez** [comment]
@Willjobs4  Calma boby, aun no he terminado

**Comment by Willjobs94** [comment]
Ahhh, sorry

**Comment by LuisAlbertoPenaNunez** [comment]
@Willjobs94 Aqui esta el resultado

![preview](https://cloud.githubusercontent.com/assets/5881238/13962765/71932816-f030-11e5-9219-f2fc6fd8a0a4.png)
