### ISSUE TITLE
Actualizar el formato de url en el servicio de twitter

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#336]
Actualmente cuando se publica un tweet, el link proporcionado esta en el formato antiguo **(http://emplea.do/JobOpportunity/Details/121-developer-junior)**, seria bueno actualizarlo al nuevo **(http://emplea.do/jobs/121-developer-junior)** para mantener la congruencia.

**Comment by Willjobs94** [comment]
I'm on it
