### ISSUE TITLE
Change the mobile app theme to match the web version

### ISSUE THREAD

**Issue by LuisAlbertoPenaNunez** [developersdo/empleo-dot-net#338]
Right now the mobile app use a different theme which doesn't match the web version

**Comment by LuisAlbertoPenaNunez** [comment]
This is how it looks now

![screen shot 2016-03-22 at 14 06 09](https://cloud.githubusercontent.com/assets/5881238/13964366/61fddb88-f037-11e5-9fb2-62a95c1df443.png)

**Comment by Willjobs94** [comment]
+1
