### ISSUE TITLE
Como usuario, quisiera especificar la cantidad de  ofertas trabajos que se muestren en la pantalla

### ISSUE THREAD

**Issue by Edulopez** [developersdo/empleo-dot-net#342]
Posiblemente el usuario va a querer ver más de 15 ofertas de trabajo cuando este filtre. Opciones podrían ser {15, 30, 50, 100}.

Actualmente, si se quieren ver más de 15, hay que modificar el querystring PageSize=15 al valor deseado.

**Comment by jpozo20** [comment]
Le echaré un vistazo durante el próximo fin de semana.

**Comment by jeanrodriguez** [comment]
veo que en la pagina de jobs hay un "mostrar mas empleos", cuando le damos click ese nos muestra un pagination, mi duda es, si se agrega un dropdown para poder mostrar mas jobs quizas deberiamos de quitar el boton de "mostrar mas empleos" y dejar la paginacion y el dropdown para cambiar la cantidad de job, @claudiosanchez @jpozo20  @RaulMonteroC (no se a quien mas etiquetar lol)

**Comment by jeanrodriguez** [comment]
ya veo porque el botton de  "mostrar mas empleos" esta, ese boton manda a la pantalla de jobs y la pantalla de jobs es la que tiene el pagination
