### ISSUE TITLE
Como usuario quiero poder hacer login con Github

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#344]

**Comment by Willjobs94** [comment]
How common is that a user not dev wants to login with github to post a job?

**Comment by RaulMonteroC** [comment]
Actualmente los logins son solo para postear un trabajo, no para los candidatos. Por tanto, una persona de RRHH o algo relacionado dudo que tenga una cuenta de github.

Si considero que sería un buen feature una vez tengamos features que necesiten login de los candidatos (upvote & downvote, Q&A, etc).

**Comment by eatskolnikov** [comment]
@RaulMonteroC en el caso de los logins encuentro que más es mejor, como solo se van a logear con cuentas sociales. Que jevi sería que el que postee la solucion sea un ceo de una de esas startups bacanas donde hasta el ceo usa github.

**Comment by RaulMonteroC** [comment]
@eatskolnikov Me parece bien ese use case. Son el tipo de cosas que queremos promover, estoy de acuerdo contigo.
