### ISSUE TITLE
Signup / Login mediante correo electrónico

### ISSUE THREAD

**Issue by jblandino** [developersdo/empleo-dot-net#345]
:smile: 
Sería bueno que puedan hacer un registro o inicio de sesión mediate las cuentas de correo electrónico.

Puede darse el caso de que una compañía (**independientemente de que sea o no de tecnología, por ejemplo una heladería que ande buscando un soporte técnico**) no tenga redes sociales pero quiera buscar un talento en el sitio.

@eatskolnikov

**Comment by rapito** [comment]
Si se estan dejando de publicar empleos porque ( por politicas de la empresa ) la persona de RRHH no puede usar su correo personal, entonces que se cree un gmail/facebook/etc con el correo de la empresa. (es lo que yo hago y no me causa problemas). 

Si este issue se cierra con la decisión de no hacerlo, entonces recomendaría agregar alguna nota en el area de elegir los servicios, explicando brevemente por qué no hay un form (o algo asi) para registrarse, junto a un friendly link que diga "crear un correo en google". 

Entiendo y comparto el punto de vista de los contribuidores principales del código. Como MVP y garantía de un market tarket, lo que hay ahora es suficiente.

**Comment by Edulopez** [comment]
Los usuarios No Tech generalmente no son amantes de crear muchos correos ni tener muchos servicios.
Existen empresas que las politicas de los correos es bastante fuerte y crear un "correo empresarial"[at]google.com puede que no este dentro de sus normas y procedimientos; o simplemente les sera muy incomodo modificar todo lo mencionado para poder postear una oferta de trabajo.

Creo que podriamos perder usuarios por lo ya mencionado. 

+1 al desarrollo del feature

**Comment by jblandino** [comment]
@Edulopez exactamente, no veo esto de crear un form como un inconveniente o algo que les tomaría 1 hora siquiera, ni algo que descentralizaria los mantenimientos de los usuarios ya que es lo mismo, es un correo electrónico.

Si lo que quieren es simplemente usuarios con Social Media Profiles realmente van a perder usuarios.
:-1: 
Así que voto al desarrollo del feature
:+1:

**Comment by eatskolnikov** [comment]
La idea detrás de no hacer este feature es que sirva de filtro para las empresas que puedan tener culturas totalitarias que bloquean los sites de social media y te ponen a trabajar con un pana detrás de tí.

**Comment by Edulopez** [comment]
@eatskolnikov Entiendo lo que dices, pero no se debe de mezclar el hecho de que bloqueen social sites, con que la empresa(o persona que trabaja como scout) tenga un social account.

En donde trabajo, por motivos de las normas ISO no se pueden tener correos no controlados por la institución al menos de que se creen políticas especiales para ellas. No creo que ellos trabajaran en excepciones fácilmente.

Eso es solo  1 caso, me imagino que otras personas tendrán sus motivos para no querer crear mas cuentas. Lo mas seguro también existen personas que simplemente no le gusta login con social accounts.

Todo esto es solo nuestra opinión. Seria bueno que más personas (ojala scouts y RRHH) comenten.

**Comment by RaulMonteroC** [comment]
Que quedamos con esto al final?

**Comment by luis-ramirez** [comment]
No quiero trabajar en una empresa en donde ni siquiera se pueda usar facebook, so, al final que gano con poder entrar con mi mail, sino quiero estar recordando passwords ni emails?

**Comment by RaulMonteroC** [comment]
Estoy de acuerdo contigo. Hagamos un pull. En este post den un reaction :+1:  o :-1:  para saber la opinion de todos. No lo hagan en el post original porque ya tiene algunos reactions entonces el conteo no sería real. @luis-ramirez @eatskolnikov @Edulopez @jblandino @rapito @claudiosanchez @developersdo/empleodotnet-team

**Comment by jblandino** [comment]
Ok entonces olviden esto, sigan usando oauth con las redes sociales, aunque no entiendo el problema de poner un simple form de login realmente pero guarebel.
👎
