### ISSUE TITLE
Estandarizar información de la vacante

### ISSUE THREAD

**Issue by abrahannunez** [developersdo/empleo-dot-net#348]
Entiendo que para un mejor funcionamiento y un mejor manejo de información, se deben estandarizar algunos datos en las vacantes. 

Exigir información de la empresa, exigir un responsable de la vacante y exigir un rango salarial para la vacante. 

Creo que vale la pena discutir las ventajas y desventajas de obligar a quien publica una vacante a especificar estos datos.

**Comment by claudiosanchez** [comment]
@abrahannunez Tú punto tiene validez, en que mejorar la calidad de la información del post añade valor. Ahora bien; el tema está en que más que tener campos standard para eso (que son fácilmente burlados), se debe de (1) influenciar a que los usuarios tengan la cultura de ofrecer toda la información y (2) en vez de imponer, podemos sugerir.

**Comment by RaulMonteroC** [comment]
Estoy de acuerdo con @claudiosanchez . Lo ideal es crear la cultura de que las personas quieran crear posts de calidad.

**Comment by abrahannunez** [comment]
@claudiosanchez @RaulMonteroC Si, me parece bien. Ahora bien, en lo que se adopta la cultura sería bueno que los post que no manejen esta calidad de publicación sean borrados y dejarle saber a quienes publican la causa.

**Comment by RaulMonteroC** [comment]
@abrahannunez Más que borrarlo, me parece mejor crear un correo estandard que describa como manejar hacer un buen post de empleo y promover que el mismo usuario la cambie. Obviamente, sera necesario que el usuario pueda editar sus trabajos.

El feature de editar trabajos y el de upvote/downvote hara que el usuario quiera tener un buen post porque sino la misma comunidad hara que el trabajo pierda visibilidad y por tanto no tenga el impacto deseado.

**Comment by RaulMonteroC** [comment]
Esto tiene unos cuantos dias, si no hay ninguna objeción asumire que último comentario es acuerdo al que llegamos @abrahannunez @claudiosanchez @developersdo/empleodotnet-team
