### ISSUE TITLE
Crear un archivo contributing.md

### ISSUE THREAD

**Issue by anyeloamt** [developersdo/empleo-dot-net#350]
Sería bueno especificar las reglas, guías o convenciones para contribuir al proyecto con este archivo. 
Así, cada vez que alguien vaya a abrir un issue o PR github le aconsejará leer la guía de contribución.

Más información [en este artículo](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) (es corto).

**Comment by Willjobs94** [comment]
Seria bueno, y pudiésemos tener algunos gif como en repos hipster.

**Comment by claudiosanchez** [comment]
Aquí un ejemplo de contributing https://github.com/rails/rails/blob/master/CONTRIBUTING.md

**Comment by claudiosanchez** [comment]
@anyeloamt Veo que el repo ya tiene parte de esto de como contribuir en el readme.md; ¿te animas a crear un PR con el contributing.md?

**Comment by anyeloamt** [comment]
@claudiosanchez lo haré.

**Comment by eatskolnikov** [comment]
@anyeloamt ¿cómo vamos? Estamos abogando por agregar los tips and tricks en el wiki, si es posible agregalos ahí :D

**Comment by RaulMonteroC** [comment]
Es mejor hacerlo en el root. Github tiene una convención que muestra un mensaje con un link al archivo cuando se esta en la pantalla de los issues. https://github.com/blog/1184-contributing-guidelines

**Comment by eatskolnikov** [comment]
Cool, @RaulMonteroC  ayuda a @anyeloamt

**Comment by RaulMonteroC** [comment]
No hay prob.

**Comment by anyeloamt** [comment]
Sorry por la tardanza.
Según veo, en el readme tenemos la guía de contributing casi completa, así que supongo que sólo habría que mover y editar un poco.
