### ISSUE TITLE
Tener un changelog del proyecto.

### ISSUE THREAD

**Issue by anyeloamt** [developersdo/empleo-dot-net#351]
El proyecto debería tener changelog, serviría para hacer tracking de bugfixes, nuevos features y otras cosas por cada versión. [Aquí un ejemplo](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/changelog.md)

**Comment by claudiosanchez** [comment]
@anyeloamt Se está usando el feature de Releases de Github. ¿Cuales son los pluses del changelog vs Releases?

**Comment by anyeloamt** [comment]
No sabía de los releases, creo que funciona bien de esa forma. 

Aunque con el changelog podríamos saber cuál será la próxima versión y qué viene con esta antes de ser lanzada. Es decir, en cada pull request se incluiría una modificación al changelog, de modo que no tendríamos que esperar a que salga el nuevo release para saber qué hay nuevo. 

Supongo que `podemos tener ambas cosas.
