### ISSUE TITLE
Padding-bottom crea margen no deseado en el footer

### ISSUE THREAD

**Issue by EliasPujols** [developersdo/empleo-dot-net#353]
Al principio pense que era el navegador, luego indagando en el codigo me percate que ese problema lo esta causando el padding-bottom del Site.css

![capture](https://cloud.githubusercontent.com/assets/12973165/14029159/ef064132-f1d6-11e5-988f-4ff4b97512c3.PNG)

**Comment by Willjobs94** [comment]
@eatskolnikov I guess we can close this one.
