### ISSUE TITLE
Poder editar trabajos

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#366]
Permitir que el usuario registrado pueda editar los trabajos que ha creado previamente.

**Comment by Willjobs94** [comment]
So @RaulMonteroC , we are going to have like an admin page for each user ? Or just a table with his jobs offers for edit and delete ?

**Comment by RaulMonteroC** [comment]
El usuario ahora mismo tiene un perfil donde se muestra el listado de trabajos que tiene. Lo unico que añadiria es un boton de editar a esos trabajos para que le cargue de nuevo el formulario con esa información para ser editada.

**Comment by eatskolnikov** [comment]
@Willjobs4 vamos a comenzar a tratar estos issues como user stories. El scope de este issue es que se puedan editar los trabajos. Con un form debería ser suficiente.

**Comment by Willjobs94** [comment]
Perfecto,
