### ISSUE TITLE
Agregar sugerencias antes de aplicar a un empleo

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#371]
Nos hemos enfocado mucho en el lado de HHRR es hora de comenzar también a darle amor a la gente que aplica. Esta sugerencia sale a partir de este post 
![screen shot 2016-03-29 at 4 43 13 pm](https://cloud.githubusercontent.com/assets/1693000/14123212/8163f4d0-f5cd-11e5-8131-bda504b37a53.png)
y de que varias veces Riaz y Jorgex han mencionado preocupaciones similares.

**User story:**
Como usuario quiero que la plataforma me aconseje la mejor forma para aplicar a los empleos

**Criterio de aceptación:**
- Crear un post con los guidelines a seguir para hacer una carta de presentación
- Que el usuario vea un link al post cerca del título de la sección "Como aplicar"

**Comment by eatskolnikov** [comment]
Gustavo accedió a hacer un resumen de los consejos que el ve necesarios a seguir.

**Comment by RaulMonteroC** [comment]
Vi el post y me gusto bastante. Esta muy buena la idea

**Comment by RaulMonteroC** [comment]
Como podría ser la implementación de esto  UI/Ux wise ? @aguacatek

**Comment by ovatsug25** [comment]
Saludos! Ya le puedo dedicar tiempo a esto. Durante el dia y para la proxima semana le estare enviando propuesta.

**Comment by jpozo20** [comment]
¿En qué quedaron estos consejos? 😛
