### ISSUE TITLE
Main page search bar context

### ISSUE THREAD

**Issue by LuisAlbertoPenaNunez** [developersdo/empleo-dot-net#374]
Let's say you are looking for a job, if you type a query into the search bar, it should only refresh the job list since that's the tab you are right now.

If you are looking for saved jobs position (Favorites), and you type text into the search bar it should filter the saved jobs by title.

**Comment by codnee** [comment]
It was agreed that the search bar wouldn't filter favorites. We decided to make it go back to search the first fragment and query the server again.
