### ISSUE TITLE
Most popular

### ISSUE THREAD

**Issue by EliasPujols** [developersdo/empleo-dot-net#379]
Como usuario me gustaria que al acceder a emplea.do pudiera visualizar cuales son los empleos mas populares del site.

**Comment by Edulopez** [comment]
Alguien esta en esto?

**Comment by RaulMonteroC** [comment]
Ya que tenemos la opción de upvote/downvote implementado sería solo ordernar por ese campo ( si es que no se hace actualmente) @anyeloamt

**Comment by eatskolnikov** [comment]
@EliasPujols intenta poner titulos un poco mas descriptivos en el futuro.

**Comment by EliasPujols** [comment]
@eatskolnikov  No volvera a suceder.
Gracias!

**Comment by anyeloamt** [comment]
@RaulMonteroC aún no se ordena por ese up/down, sería nice tener un `order by` en el UI para que el usuario pueda especificar por qué campo quiere ordenar (popularidad, fecha de publicación, etc)

**Comment by RaulMonteroC** [comment]
@anyeloamt Estoy de acuerdo contigo. Solo que para el up/down vote debe ser un defecto porque eso permite que los trabajos categorizados como malos pierdan visibilidad al colocarse al final.

**Comment by anyeloamt** [comment]
@RaulMonteroC tienes razón.

**Comment by RaulMonteroC** [comment]
Esto depende del issue #308
