### ISSUE TITLE
Como usuario quiero que mi anuncio se postee en la página de facebook de emplea.do

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#381]
Cuando cree un puesto de trabajo postealo automáticamente en la pagina de facebook de emplea.do
(https://developers.facebook.com/docs/pages/publishing)

**Criterio de aceptación:**
- Que se comparta el link del puesto https://www.facebook.com/empleadonet/ al crear una posición
- Que en el post aparezcan los primeros 25 caracteres de la descripción
- Si es un trabajo remoto que aparezca el hashtag #weworkremotely en la descripción

**Comment by jpozo20** [comment]
Veré si puedo hacer algo con esto el próximo fin de semana.

**Comment by christianrd** [comment]
@eatskolnikov @jpozo20 @RaulMonteroC @DannyFeliz Este feature esta resuelto o puedo realizarlo?

**Comment by DannyFeliz** [comment]
@christianrd No está resuelto aún, puedes realizarlo 🛴

**Comment by eatskolnikov** [comment]
@christianrd dale
