### ISSUE TITLE
Evitar publicaciones de vacantes falsa(Spam).

### ISSUE THREAD

**Issue by christianrd** [developersdo/empleo-dot-net#388]
Creo que sería importante tener el control de las vacantes que se publican para no tener usuarios de la magnitud como se muestra en la imagen adjunto. Sería bueno que cada usuario que publica vacante tenga que registrarse, un administrador que verifique los post antes o después de publicarse o un filtro de palabras.

![romo emplea do](https://cloud.githubusercontent.com/assets/10536381/14236643/94932f86-f9e6-11e5-9dee-bf4447d47b66.png)

![emplea do emplea_do twitter](https://cloud.githubusercontent.com/assets/10536381/14236786/ca8c7ff0-f9e8-11e5-909d-5e621d7d9c86.png)

**Comment by Willjobs94** [comment]
That's terrible, we should delete it ASAP @eatskolnikov

**Comment by eatskolnikov** [comment]
Se puede intentar hacer algo para evitar este tipo de cosas, o al menos alertarlas.

**Comment by RaulMonteroC** [comment]
Se supone que esto debe reducirse con el login social.

**Comment by eatskolnikov** [comment]
@RaulMonteroC si, pero vamos a aprovechar este issue para proponer más cosas

**Comment by anyeloamt** [comment]
Aparte del down/up vote, podríamos ponerle una opción de "Report abuse", así desde la aplicación los usuarios podrían reportar una publicación. se informaría a los admins (cuando hayan) para que revisen.

**Comment by RaulMonteroC** [comment]
Lo que dice @anyeloamt es muy buena idea. Yo añadiria que el "Report abuse" envie un correo de notificación a los admins que tengan los permisos para eliminar esa info de producción (hasta que el issue #235 se concluya)

**Comment by luis-ramirez** [comment]
Esto se resolvio en el relase 0.4.0.0
