### ISSUE TITLE
Filtro de "Buscar solo empleos remotos" se pierde al utilizar la paginación

### ISSUE THREAD

**Issue by Jeremy410** [developersdo/empleo-dot-net#395]
Al momento de seleccionar la casilla "Buscar solo empleos remotos"  y presionar algún botón, la paginación se pierde.

1.- Buscando empleos remoto:
![remote search](https://cloud.githubusercontent.com/assets/8070933/14263302/e85662ae-fa87-11e5-96d6-7e8431b0201a.PNG)
2.- Seleccionar botón número 2 de la paginación.
![remote search ii](https://cloud.githubusercontent.com/assets/8070933/14263148/fe364e3c-fa86-11e5-826a-05344bfb4db1.PNG)

Resultado:
![remote search iii](https://cloud.githubusercontent.com/assets/8070933/14263307/eff4ef26-fa87-11e5-99d0-db715ee64803.PNG)
![remote search iv](https://cloud.githubusercontent.com/assets/8070933/14263346/198116a8-fa88-11e5-8e3a-ba290958090c.PNG)

**Comment by RaulMonteroC** [comment]
Al parecer @codnee ya habia tomado esto. Así que te regreso el ownership y lo que estaba trabajando lo colocare en otro issue (referente al eliminar fields vacios del query string).
