### ISSUE TITLE
Como usuario quiero poder incrustar mi listado de trabajos a mi sitio web

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#398]
Hay empresas que tienen una página de empleos en su sitio web, agregando este feature ellos podrían usar emplea.do e incrustar el listado en su pagina web.

Voy a escribir como lo veo en el final y de ahí decidimos que va y que no va. Tomad en cuenta que estás son solo sugerencias y el MVP de este feature no va a llevar todo:
- Agrupar los trabajos por categoría
- Permitir incrustar el listado completo de trabajos
- Permitir incrustar trabajos de una categoría específica
- Permitir la omisión de puestos específicos en el código de incrustación
- Permitir incrustar una version en lista y una versión en grid del listado de trabajos

**Comment by RaulMonteroC** [comment]
Deja ver si entiendo, la idea es que ellos puedan incrustar en su página empleos provenientes de emplea.do ?

**Comment by eatskolnikov** [comment]
Si

**Comment by RaulMonteroC** [comment]
De acuerdo. El único beneficio que le veo a esto es que la empresa pueda tener acceso a los trabajos publicados (en emplea.do) desde otra página para evitar que tuviera que postearlo dos veces. 

Para esto, se me ocurre dos alternativas

1. **API público (con dev credentials):** Usar un API para que puedan acceder a la información de los trabajos que ellos administran  y mostrarla en su página de acorde a sus necesidades

2. **Widget configurable:** Algo parecido a los widgets de twitter que aparecen en algunos blogs. En este caso, solo sería incrustarlo en la página que lo quiera y configura lo que se desee mostrar.
