### ISSUE TITLE
La invitación a usar el Wizard está muy "cutre"

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#407]
El mensaje para que utilizes el feature de Wizard está muy cutre. No es vistoso y realmente no me anima a irme por el Wizard. 

![screen shot 2016-04-07 at 11 32 52 am](https://cloud.githubusercontent.com/assets/2293759/14356809/409bdb8c-fcb4-11e5-8af6-11407f1f7620.png)

**Comment by Jeremy410** [comment]
¿Qué te parecen estas opciones?

1.- ¿Requieres de ayuda para publicar tu empleo? Prueba <strong>click aquí</strong>
2.- ¿No sabes cómo empezar? <strong>Acá</strong> te ayudamos a crear tus empleos.
3.- ¿Confuso para ti? Crea tu empleo paso a paso <strong>aquí</strong>
