### ISSUE TITLE
Crear un servicio para que se pueda hacer A/B Testing automáticamente

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#409]
La idea es que cuando se implemente una pantalla nueva se tenga un servicio que muestre la pantalla vieja o la nueva aleatoriamente a los usuarios y tomemos feedbacks, así sabemos si el cambio fue bueno y si a los usuarios les gusta.

**Comment by claudiosanchez** [comment]
Requerimientos adicionales
- Tener la capacidad de asignar un factor (Ejemplo: A el 15%, B el 85%)
- Tener la capacidad de configurar esto de forma especifica por cada feature
