### ISSUE TITLE
Refactoring para Locations

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#41]
En el ejemplo del último hangout agregamos un filtro para la localidad geográfica, pero la forma como se sacan todas las localidades es muy ineficiente. Quizás se puede crear una nueva entidad/tabla para almacenar las ciudades?

**Comment by hansselabreu** [comment]
Intentaré hacer eso.

**Comment by hansselabreu** [comment]
Bueno casi lo llego a hacer, hice la Entidad Location y le agregué un ForeignKey a JobOpportunity. Todo funcionó de maravillas en el proyecto, menos en la parte de crear una nueva vacante:

 The associated metadata type for type 'EmpleoDotNet.ViewModel.NewJobOpportunityViewModel' contains the following unknown properties or fields: LocationId. Please make sure that the names of these members match the names of the properties on the main type.

Como apenas tengo pocos días que empecé ASP.MVC voy a tratar de prepararme mejor para dar con la solución.

**Comment by hansselabreu** [comment]
Bueno ya lo he arreglado. El TODO: seria hacer que cuando se seleccione la localidad en la cual aún no haya vacante muestre un aviso de que no hay. Pero por ahora redirige al Index.

**Comment by amhed** [comment]
No marques el issue resulto hasta que sea revisado por alguien más. Hiciste un pull request con estos cambios?

**Comment by hansselabreu** [comment]
Lo siento, ni sé como lo marqué resuelto. Apenas me acostumbro a git/github.
