### ISSUE TITLE
Crear rss feed de los trabajos

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#417]
Como usuario quiero tener acceso a un RSS feed de los trabajos en la plataforma.
Criterio de aceptación:
- Cuando acceda a http://emplea.do/rss quiero ver un xml con el formato de un rss feed. 
- Cuando coloque la url en http://www.feedvalidator.org/ debo recibir un resultado positivo
- Cada item debe tener el logo de la empresa y la descripción del puesto

**Comment by Eduardoveras94** [comment]
Lo veo muy util, good idea, no _deberia _ser dificil de implementar

**Comment by RaulMonteroC** [comment]
Mete mando entonces @Eduardoveras94

**Comment by Willjobs94** [comment]
@eatskolnikov, Estoy trabajando con este issue y según el standard de [RSS](http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt) el único que tiene imagen es el channel, es decir el feed, pero no cada item.
