### ISSUE TITLE
Add local caching of Favorites.

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#418]
As a user I want to have my favorite positions available even when I don't have an internet connection. I want an easy way to set a position as a favorite and have it locally cached for future visits.

**Comment by eatskolnikov** [comment]
Interesante. ¿Qué estrategía quieres usar? ¿Cookies? ¿Localstorage?

**Comment by jugomez** [comment]
@eatskolnikov Creo que @codnee creo este issue para mobile... Cookies no aplican.

**Comment by davidtavarez** [comment]
Están usano akavache https://github.com/akavache/Akavache

**Comment by Willjobs94** [comment]
@davidtavarez use markdown for links. just a suggestion.

**Comment by codnee** [comment]
I will do this.

@LuisAlbertoPenaNunez and I discussed doing this in the LongClick event of the ListView in the Jobs fragment. This would be an easy single-step way of getting this done, and it does not need to change the UI.

**Comment by codnee** [comment]
As per #460 this is not going to be included in the MVP.
