### ISSUE TITLE
Web API Architecture for Mobile

### ISSUE THREAD

**Issue by Willjobs94** [developersdo/empleo-dot-net#421]
We need some feedback to start with the web api implementation for mobile.

**Comment by anyeloamt** [comment]
#90

**Comment by claudiosanchez** [comment]
Feedback on what? What are you proposing? @Willjobs94

**Comment by AIsaac08** [comment]
¿Por qué hubo que abrir un nuevo issue cuando ya existía uno sobre lo mismo? O.o

**Comment by Willjobs94** [comment]
Los DTOs, de los que se habla en el issue #90 estarían en la solución Mobile o en la de .NET.

**Comment by codnee** [comment]
Lo dices o lo preguntas? For the record, estan en **Api.Contract**.

**Comment by anyeloamt** [comment]
Supongo que se refiere a que se defina cómo se va a desarrollar el feature.

¿Se va a utilizar WebApi?
¿Se va a agregar un nuevo proyecto al Solution o se hará un controller nuevo para el API y ya?
¿Se utilizará OAuth o alguna otra librería?
¿Se van a copiar los DTO de **Api.Contract** al Solution de **EmpleoDotNet** (Las aplicaciones están en solutions diferentes)?
Etc.

**Comment by Willjobs94** [comment]
Yeah, lo que dice @anyeloamt,
+ O si vamos a utilizar el mismo controller y agregarle los métodos necesarios para el api

**Comment by codnee** [comment]
- No estoy seguro, pero creo que si.
- Se creara un nuevo proyecto al Solution.
- El Api sera read only por ahora, así que no se utilizara nada de eso.
- No se copiara nada, se referenciará el proyecto.

**Comment by jpozo20** [comment]
Creo que con el #522 ya se puede cerrar este issue.
