### ISSUE TITLE
Dejar de hacer pases a producción a peluche™

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#424]
Configurar el CI

**Comment by luis-ramirez** [comment]
@hminaya te buscan hay que configurar TeamCity para que corra los migrations

**Comment by hminaya** [comment]
Ya le di el training a @jgtaveras ... Estoy esperandolo a el para hacerlo en conjunto y esparcir el conocimiento. El viene para mi casa hoy, le voy a tirar la pelota
