### ISSUE TITLE
Mobile: Revisit cache service.

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#426]
According to [Akavache#271](https://github.com/akavache/Akavache/issues/271) LocalMachine stores data in cache directories that may be cleaned by the OS.

The cache service should offer two tiers of caching, one volatile for things that are not essential (i.e. last places searched) and one persistent for things that are (i.e. favorites).

**Comment by claudiosanchez** [comment]
This can be simply addressed by expiration. No need to have tiers of caching if that's the only requirement.

**Comment by codnee** [comment]
Fair enough, so the tasks needed are:

- Using persistent storage in the cache service.
- Using expiration for short-lived objects.
