### ISSUE TITLE
Mapa con las ubicaciones de los trabajo/ geolocation de cada trabajo

### ISSUE THREAD

**Issue by Eduardoveras** [developersdo/empleo-dot-net#428]
Seria un buen new feature tener un mapa con la ubicacion de los trabajos disponibles, no se poner tags pero seria un #NewFeature

![jobmonster-wordpress-theme](https://cloud.githubusercontent.com/assets/4433495/14499587/eaa362c8-016c-11e6-82af-6d79e50ae871.jpg)

**Comment by anyeloamt** [comment]
Suena jevi, yo le agregaría que cuando entre al site me recomiende los trabajos que estén cerca de mi.

**Comment by Willjobs94** [comment]
@anyeloamt, eso puede ser otro issue.
