### ISSUE TITLE
Múltiples Votos a una Posición

### ISSUE THREAD

**Issue by iajrz** [developersdo/empleo-dot-net#429]
Es posible hacer varios votos utilizando el modo incógnito del navegador.
Identifico como posibles soluciones:
- requerir autenticación para ejercer el voto
- implementar fingerprinting (probablemente out of scope)

**Comment by Willjobs94** [comment]
I guess authentication is the right one by now

**Comment by RaulMonteroC** [comment]
Si, creo que lo que deberiamos trabajar es en la autenticación de candidatos. @anyeloamt toma esto en cuenta como estas haciendo el profile (issue #100) si necesitas ayuda con algo, me dices.

**Comment by luis-ramirez** [comment]
Pero ya esto esta en produccion, no?

**Comment by RaulMonteroC** [comment]
El up/down vote si. La autenticación para candidatos no. Ahora mismo la autenticación es solo requerida para que las empresas puedan publicar una vacante. La funcionalidad del up/down vote utiliza localstorage según entiendo para validar si puedes (o no) hacer una votación.
