### ISSUE TITLE
Add twitter meta tags

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#430]
As a twitter user I want to get as much information as possible without having to leave twitter, and only click if the info is interesting to me. I would like sites that publish automated tweets when content is created to use the relevant, and twitter specific, meta tags that will allow twitter to show a preview of the link.

This will also leave more space for hashtags (i.e. #380 ) and retweets.

**Comment by Willjobs94** [comment]
how can we test this feature without merging it on ci ? I mean how can I tweet something to check if my meta tags are working ?

**Comment by RaulMonteroC** [comment]
@Willjobs4 Check out the way the twitter service is been tested (for unit test) in the project. That should give you an idea.

**Comment by Willjobs94** [comment]
@RaulMonteroC  I mean, how can I see my posted tweets ? Do I need to create a developer account on twitter or emplea have some dev twitter credentials for twitter ?

**Comment by RaulMonteroC** [comment]
no idea. I think @luis-ramirez was the one to do the twitter posting service, maybe he can give you an idea.

**Comment by ajpinedam** [comment]
Twitter requiere que se cree una cuenta de developer y para poder salir el "card" con la información que deseemos debemos pasar por un proceso de aprobación el cual hasta la ultima vez que me toco era un proceso tedioso.
