### ISSUE TITLE
Como usuario quiero poder eliminar una posición que creé

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#435]
Ahora mismo se está haciendo a peluche®

Criterio de aceptación:
- En el listado de mis posiciones debo ver un botón de eliminar
- En el detalle de mi posición debo ver un botón de eliminar
- Antes de eliminar una posición debe pedirme confirmación
- Al eliminar una posición debe mostrarme un mensaje de que la posición fue exitosamente eliminada

**Comment by Willjobs94** [comment]
This would be a soft delete ?

**Comment by eatskolnikov** [comment]
Si

**Comment by Willjobs94** [comment]
@RaulMonteroC @eatskolnikov I guess we can close this one.
