### ISSUE TITLE
El footer no se posiciona al fondo

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#442]
Cuando no hay suficiente contenido, el footer no baja al fondo de la página.

![capture](https://cloud.githubusercontent.com/assets/4156062/14677999/049b9e0a-06e2-11e6-902f-dac3ea30b502.PNG)

**Comment by eatskolnikov** [comment]
Chequea http://getbootstrap.com/examples/sticky-footer/

**Comment by RaulMonteroC** [comment]
Este error no se ha corregido aún. Sucede con resoluciones de pantalla grandes.

**Comment by Willjobs94** [comment]
@RaulMonteroC, @eatskolnikov I consider that we can close this one
