### ISSUE TITLE
Cambiar menu para desplegarse en el top bar.

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#443]
Mover el menú del sidebar hacia el top bar cuando se este visualizando desde un dispositivo lo suficientemente grande. Para la version movil (smartphones) lo podemos dejar como esta o cambiarlo para que se despliegue en un listado hacia abajo partiendo del top bar.

Ejemplo full scale site

![capture](https://cloud.githubusercontent.com/assets/4156062/14710233/9007195e-07a2-11e6-87c3-de1a79b01c72.PNG)

Ejemplo Mobile
![capture 2](https://cloud.githubusercontent.com/assets/4156062/14710306/df983dea-07a2-11e6-8299-596ab2f26448.PNG)

Referencia de las imagenes: http://wp.nootheme.com/?theme=jobmonster

**Comment by jortiz6564** [comment]
Puedo hacer esto!

**Comment by RaulMonteroC** [comment]
@jortiz6564 Dale para alla entonces.
