### ISSUE TITLE
Al hacer una búsqueda la url se carga con parametros vacíos

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#446]
Cuando se hace una búsqueda de algún trabajo, el query string viene cargado con todos los parametros aún si estos se han dejado vacíos.

Aquí un screenshot de lo que sucede cuando se le da al buton buscar dejando todas las opciones de búsqueda en blanco.

![capture](https://cloud.githubusercontent.com/assets/4156062/14751144/784de5fa-0896-11e6-868f-b05417a30714.PNG)

**Comment by jgtaveras** [comment]
y esto es un problema por ??? @RaulMonteroC

**Comment by eatskolnikov** [comment]
@RaulMonteroC secundo a @jgtaveras This is not an issue

**Comment by RaulMonteroC** [comment]
No es que sea un problema. La aplicación funciona bien con eso, es más para que no se vea tan feo cuando compartes esa url con alguien más por ejemplo.Yo prefiero que diga http://emplea.do?remote=true a tener todo eso colocado sin necesidad.
