### ISSUE TITLE
Mobile: Reorganize files and namespaces

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#449]
The current file and namespace structures of the Mobile solution are a bit too messy.

We should clean them up.

**Comment by LuisAlbertoPenaNunez** [comment]
Dale, es un cambio trivial

**Comment by LuisAlbertoPenaNunez** [comment]
Imma take this one

**Comment by Willjobs94** [comment]
@RaulMonteroC, @eatskolnikov I guess we can close this one.
