### ISSUE TITLE
Consider having the JobDetails show in a separate Activity

### ISSUE THREAD

**Issue by codnee** [developersdo/empleo-dot-net#450]
As a user with a small phone I want to be able to see the details of a position without having to scroll too much.

This is what the details screen currently looks like, only 2/3 of the screen are available for you to see the details of the position.

![13059527_679963508809668_138011733_n](https://cloud.githubusercontent.com/assets/5662780/14764877/d43fe1aa-0996-11e6-98c2-8dbdf3cfb463.png)

Moving the the JobDetails to its own Activity would give the user more space to see the content of the position and interact (share, up/down vote/comment...) with it.

@claudiosanchez @LuisAlbertoPenaNunez thoughts?

**Comment by claudiosanchez** [comment]
Another strategy would be to make the current Layout change to hide the Search and header area.

**Comment by codnee** [comment]
Indeed. However, a separate activity would let us keep it simple, as we wouldn't be changing stuff in outer UI back and forth.

**Comment by LuisAlbertoPenaNunez** [comment]
Even using a Fragment would make it even easier, since it's just a **replace** fragment transaction.
@codnee

**Comment by codnee** [comment]
Wouldn't we also have the menu options updated to give the user more interactions with the position? That is what I meant by saying we'd have to change the UI back and forth. 

We could also make that other Activity Browsable with a custom scheme via its intent filter. So when a user shares a link it does not point to the website, but to the app.

**Comment by codnee** [comment]
@LuisAlbertoPenaNunez  a replace fragment transaction will be.
