### ISSUE TITLE
Facilitar el onboarding de nuevos contribuyentes

### ISSUE THREAD

**Issue by EfrainReyes** [developersdo/empleo-dot-net#451]
Actualmente, cuando una persona descarga su repositorio, para poder correr el proyecto en su máquina debe conseguir por cuenta propia los keys para varias variables de configuración.

Un problema con esto, aparte del hecho de que el dev debe buscar los keys por su cuenta, es que el web config retiene esos cambios en git, y el dev debe asegurarse de que esos cambios se mantengan unstaged antes de hacer un commit.

Estoy abriendo este issue para ver si encontramos maneras de hacer el proceso de onboarding y de contribuir código nuevo más cómodo, pero sin variar drásticamente la configuración que tenemos del lado de devops.

Una sugerencia es delegar los appsettings a un archivo .config distinto, al que no se le haga tracking, para que el dev pueda ingresar los keys necesarios sin tener que preocuparse por mantener ese archivo unstaged.

Otras sugerencias son bienvenidas.

cc @claudiosanchez @hminaya @eatskolnikov @jgtaveras @RaulMonteroC

**Comment by eatskolnikov** [comment]
Hay un archivo llamado base_auth.config, la idea es que la gente copie ese archivo, le quite el base_ y cambie los valores de los keys. El archivo auth.config ya está siendo ignorado en git así que los cambios nunca van a ser stagged.

**Comment by Willjobs94** [comment]
He actualizado algunas de las referencias en el wiki, para facilitar a los nuevo contribuyentes. 
Y cree una sección que muestra como poner el app [up and running](https://github.com/developersdo/empleo-dot-net/wiki/Up-&-Running).

**Comment by iajrz** [comment]
Sería cool linkear a esa página particular desde el README.md

**Comment by dfana01** [comment]
Existe la posibilidad de dokerizar la aplicación ? y hacer uso del el feature que tiene Docker 
para este fin. Referencia: https://docs.docker.com/compose/env-file/ ? Sería un cambio muy drástico ?
