### ISSUE TITLE
Error cuando entras al perfil y no tienes trabajos publicados

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#452]
<img width="1440" alt="screen shot 2016-04-24 at 11 52 59 pm" src="https://cloud.githubusercontent.com/assets/6517152/14773425/de50d028-0a77-11e6-9192-1024cd751b39.png">

**Comment by RaulMonteroC** [comment]
Alguien trabajando en esto ya?

**Comment by RaulMonteroC** [comment]
No he podido dar con el error. Cuales fueron los pasos para que esto ocurriera ? Probe (desde mi maquina)  iniciando sesión con google y facebook.

![screen shot 2016-04-25 at 12 06 05 am](https://cloud.githubusercontent.com/assets/4156062/14773580/8b7fb83a-0a79-11e6-812a-5eaee90fd7b3.png)

**Comment by luis-ramirez** [comment]
Session state :P, eso solo te ocurre cuando tienes una cookie vieja, lo cerre.
