### ISSUE TITLE
Al filtrar por trabajos remotos e ir a la segunda pág de resultados, se quita el filtro

### ISSUE THREAD

**Issue by RoxannaBatista** [developersdo/empleo-dot-net#462]
Al seleccionar el check de "BUSCAR SOLO EMPLEOS REMOTOS" y hacer clic en BUSCAR, ahora mismo salen dos páginas de resultados:
![image](https://cloud.githubusercontent.com/assets/10008991/14798250/99fa356c-0b04-11e6-926b-b90dbbf95f14.png)

Y cuando se hace clic en la segunda página se quita el check de "remote only" y no se muestra el contenido de la segunda página de remote only sino la segunda página de hacer la búsqueda sin ningún filtro:

![image](https://cloud.githubusercontent.com/assets/10008991/14798289/e1c2459c-0b04-11e6-90c3-f7b854a4f4d5.png)

**Comment by RaulMonteroC** [comment]
Hola @RoxannaBatista, este issue ya se ha trabajado y corregido anteriormente (#395). Lo único que no esta en producción aún. Para hacer pruebas te recomiendo que utilices el entorno de pruebas http://ci.emplea.do. Ahí esta al día con todos los features que hemos implementado.

**Comment by RoxannaBatista** [comment]
Oh... Intenté buscar algún issue que dijera "remoto" antes de postear este, pero no lo encontré. Anyways, gracias, usaré la versión que me indicas.

**Comment by eatskolnikov** [comment]
@RoxannaBatista La version de http://ci.emplea.do es un site de prueba, no es producción. Gracias por abrir el issue de todas formas, a ver si publicamos más seguido :P
