### ISSUE TITLE
Como usuario, si el joel test no aplica para la posición que busco el test no debería mostrarse

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#466]

**Comment by RaulMonteroC** [comment]
En que caso no aplicaría, por ejemplo ?

**Comment by eatskolnikov** [comment]
@RaulMonteroC trabajos que tienen que ver con administración de servidores

**Comment by RaulMonteroC** [comment]
Ah entiendo. El Joel test debe estar disponible solo para trabajos relacionados a desarrollo  por tener preguntas especificas de esta área.

**Comment by jpozo20** [comment]
¿Esto está resuelto? @eatskolnikov @RaulMonteroC

**Comment by Willjobs94** [comment]
@jpozo20 I think is not solved yet.
