### ISSUE TITLE
Simplificar el footer

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#471]
Actualemente el footer tiene dos partes. Estaba pensando que sería mejor colocarlo en un solo nivel y así aprovechar más el espacio. Qué opinan ?

En la imagen pueden notar los dos niveles a los que me refiero. Uno exclusivo para las redes sociales y otro para todo lo demás.

![capture](https://cloud.githubusercontent.com/assets/4156062/14920191/483fb898-0dfa-11e6-9232-8ad97c3a6088.PNG)

**Comment by juank1791** [comment]
![footer-empleo dox](https://cloud.githubusercontent.com/assets/13596890/16827987/a451f570-4959-11e6-8748-d4aa44cd1c91.png)

Mi propuesta para simplificar el footer

**Comment by eatskolnikov** [comment]
@juank1791 Gracias por la propuesta, pero tengo un par de feedbacks. ¿Puedes agrupar los botones de un solo lado?
@claudiosanchez tiene un ojo para estos detalles, dejaré que el de su opinión al respecto

**Comment by juank1791** [comment]
@eatskolnikov Se puede , pero esperare el feedback de la persona que dijiste para trabajarlo todo los feedbacks

**Comment by jpozo20** [comment]
Hice unas cositas a ver que opinan, Estas son las vistas en las versiones xtra-large y xtra-small
CC: @eatskolnikov @RaulMonteroC 

Le quite la rayita abajo ya que al poner los elementos del newsletter con text-center el :after se vuelve loco, y simplifique el mensaje de github para que queden mas organizados los botones.

Xtra-Large:
![footer-1](https://user-images.githubusercontent.com/9166182/32757474-110c7abe-c8b6-11e7-9a71-fa2392fd3003.png)

Xtra-Small
![footer-2](https://user-images.githubusercontent.com/9166182/32757475-1123485c-c8b6-11e7-9909-b037f463bc89.png)
