### ISSUE TITLE
Como usuario, quiero ver los trabajos en orden de aceptación (Likes/Dislikes) 

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#472]
Actualmente el home page me muestra trabajos recientes, pero no tengo una capacidad de ordenar por los mejores trabajos (los que tienen más likes).

**Comment by Willjobs94** [comment]
@RaulMonteroC Creo que podemos ponerle el label de UX/UI a este, no ? Estaba tratando de hacer la UI para esto y resultó ser horrible.
