### ISSUE TITLE
El correo de los puestos no se está viendo

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#475]
Aunque la gente puede poner su "Como aplicar" el correo de la compañía debe aparecer en el perfil de la compañía

**Comment by Willjobs94** [comment]
@eatskolnikov, @RaulMonteroC, considero que a este issue pudiésemos ponerle el label de `bug` ya que si no se muestra el correo, no se puede aplicar

**Comment by Willjobs94** [comment]
@eatskolnikov  a que te refieres con mostrar el correo en el perfil de la compañía ?
 * ¿Qué el usuario pueda ver el perfil de la compañía ? (otro issue)
 * ¿Qué cuando esté logeado como empresa pueda ver mi perfil y mi correo ? (Creo que no es esto) ya que esto ya lo hace
![screenshot 2016-04-30 15 23 48](https://cloud.githubusercontent.com/assets/10265964/14938105/9b20db4e-0ee7-11e6-8daf-3ad6204ff915.png)
 * ¿Qué simplemente se muestre siempre el correo de la compañía independientemente de lo que ponga en el campo "como aplicar"? (lo que implica que la persona que postea la oportunidad de empleo puede poner el correo en dicho campo y entonces se vea algo como esto )
![screenshot 2016-04-30 15 29 40](https://cloud.githubusercontent.com/assets/10265964/14938135/65c8773a-0ee8-11e6-9f07-b37f90c82ab9.png)

**Comment by eatskolnikov** [comment]
Qué simplemente se muestre siempre el correo de la compañía independientemente de lo que ponga en el campo "como aplicar"

**Comment by Willjobs94** [comment]
@eatskolnikov creo que podemos cerrar este.
