### ISSUE TITLE
User needs to complete their user profile and email validation before being able to post a job

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#478]
Feature 1 -> User Profile with email
Feature 2 -> Email Validation
Feature 3 -> Require a valid email before being able to post a job

**Comment by RaulMonteroC** [comment]
@eatskolnikov En que se quedo al final? La validación del correo se puede hacer a través del social login? puede que sea un bug el hecho de que haya cuentas con emails vacios?
