### ISSUE TITLE
Mejorar ruta para request por location

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#48]
Ahora mismo el URL resulta así:
/JobOpportunity?SelectedLocation=Puerto+Plata

Sería mejor usar el ID: 
/JobOpportunity?SelectedLocation=3

O aún mejor, combinar el Id con una URL bien formada (SEO friendly) y agregar una ruta personalizada:
/JobOpportunity/Location/3/Puerto-Plata :horse:

**Comment by hansselabreu** [comment]
ahmed, mejoré la url para que se pase el id.

**Comment by FrancisTV** [comment]
heyy estoy trabajando el url del proyecto pero no logro hacerlo de esta forma /JobOpportunity/Location/3/Puerto-Plata, el caso es que tengo una dura en esa parte hay que hacerlo directamente en routing.config o se puede hacer en el mismo controlador de le prefijo [routeprefix] de esa forma no me sale aunque alomejor seria porque hay que crear un parámetro como int? id que me dicen alguien le ha puesto la mano a eso?

**Comment by amhed** [comment]
Hazlo por partes. Lo que necesitas primero es una ruta que sea: /JobOpportunity/Location/{Id}/{Texto}

El texto puede ser lo que sea al final. Si te fijas, estas dos URLs llegan al mismo sitio:
- https://signalvnoise.com/posts/3846-lead-android-at-basecamp
- https://signalvnoise.com/posts/3846-thu-real-url

La ruta solo usa el int. Lo demás es decoración para que se vea bonito en google/sea facil de leer :)

**Comment by FrancisTV** [comment]
aaaa ok deja ver entonces.thanks

**Comment by FrancisTV** [comment]
una pregunta a la hora de custom routes que ustedes lo han hecho pasandole un parametro al index o llamandolo desde otro action? tengo duda con eso

**Comment by amhed** [comment]
Ahora mismo está en el index, pero creo que debería ser un action aparte para que quede claro

**Comment by hansselabreu** [comment]
ahmed yo he hecho que se pueda acceder a los puestos por localizaciones de esta forma: JobOpportunity/Location/2 (ejemplo), pero cuando le doy al botón filtrar sigue mandando el querystring:
JobOpportunity/Location?SelectedLocationId=2

**Comment by amhed** [comment]
http://stackoverflow.com/questions/19053512/how-do-i-get-a-pretty-url-when-creating-a-link-in-a-razor-view

=D

**Comment by FrancisTV** [comment]
haci mismo me pasaba ami

**Comment by FrancisTV** [comment]
y yo lo hacia desde el mismo index, poreso pregunte que si habia que hacerlo desde otro action

**Comment by FrancisTV** [comment]
heyy y no se puede hacer agregando un parametro int id en el actionresult index y desde el view index declarar el action ? estoy pullando de todavia no he encontrado la forma correcta de hacerlo alguien me podria dar un sugerencia, @amhed   vi una posible forma de hacerlo desde la url starkoverflow que pasaste pero no entendi como hacerlo asi.

**Comment by amhed** [comment]
La primera respuesta en stackoverflow tiene el código exacto a usar. La otra opción sería agregarlo manual (con un string)

—

**Comment by FrancisTV** [comment]
hey una cosa como puedo agregarlo manual mediante un string al meno que alguien me pueda guiar como solucionar ese issue ya que todavia no he lograrlo hacerlo quisas porque todavia no he compredido la forma de usar url.action correcta de donde va y como se hace, alguien help me?

**Comment by amhed** [comment]
Usa RouteAction en vez de Action (hay un link a un ejemplo en stackoverflow arriba)



—

**Comment by hansselabreu** [comment]
ahmed, de la forma en que la tengo tiene los siguientes bugs:
Cuando se pasa el id {0 y 1} muestran las vacantes de Santo Domingo, aun cuando en el controller tengo una condición de que si el id pasado es menor a 1 redirija a Index sin argumentos.
-Si se pasa algo que no sea int a Location (por ejemplo: JobOpportunity/Location/olaKase) la aplicación explota.

**Comment by hansselabreu** [comment]
Ok resolví el segundo bug dandole un valor predeterminado al parámetro

Pero el primer bug sigue:
Selecciono una provincia y le doy a filtrar, despues en la url aparece el id 0 no importa si es santo domingo (id==1), o cualquiera, y si le doy de nuevo a filtrar aparece el id correcto.

**Comment by amhed** [comment]
Vamo a verlo mañana. Podemos hacer otro hangout y compartes tu pantalla

**Comment by FrancisTV** [comment]
bueno si creo que seria muy bueno ese hangout asi lo que estamos aprendiendo podemos ver esa parte que en mi caso me ha dado mucha brega, avisen a que hora seria bueno entrar a gitter y acordar la hora que fuera bueno a misma hora de hangout pasado creo que fue como a la 5pm

**Comment by amhed** [comment]
Voy a hacer lo posible por estar a las 5 PM aquí.

**Comment by FrancisTV** [comment]
@hansselabreu  en mi caso ahme paso unas posibles forma en starkoverflow pero esese url.action se lo paso desde la vista pero me tira un bug

**Comment by FrancisTV** [comment]
tu el id se lo pasa en forma string o en int?

**Comment by hansselabreu** [comment]
en int

**Comment by hansselabreu** [comment]
Francis seria buen hablar por chat ya que se le llenará la bandeja de entrada de mensajes a los participantes de este issue

**Comment by FrancisTV** [comment]
una pregunta coloque este codigo de esta forma en la vista
@{
@Url.RouteUrl("Default", new {controller = "JobOpportunity", action = "Index" ,  id = @ViewBag.ID })
}  el caso es despues de este ejemplo lo que sigue es personalizar esa ure en el routing.config
?

**Comment by amhed** [comment]
Acabo de hacer un pull request sobre esto. Cojan para allá para ver la discusión: 
https://github.com/developersdo/empleo-dot-net/pull/59
