### ISSUE TITLE
As a Jobs Approver i want to be able to approve/decline job posts

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#480]
A certain group of users will be able to approve or decline jobposts
- Add the role "JobsApprover"
- Add a panel for "Pending Approval Jobs"
- From the panel approvers can Approve or Block users. If a user posts something that is not approved it is game over, there are no "continues".

Acceptance criteria:
- When i log in i should see the list of jobs pending approval
- When i reject a job post the user should be blocked

this depends on https://github.com/developersdo/empleo-dot-net/issues/479

**Comment by Willjobs94** [comment]
I guess this is also related or depended on this one #235

**Comment by RaulMonteroC** [comment]
No necesariamente, podriamos agregar esta parte en la misma aplicación que tenemos ahora para que el usuario no tenga que acceder a otro portal, sino que lo vea todo desde ahi mismo.

Me hace más sentido porque el rol de JobsApprover se le dara a usuarios comunes y no es algo de un superusuario (que es el que utilizaria el backend app).

**Comment by codnee** [comment]
There should be _trusted users_, whose posted jobs don't have to be approved, and just as users are _blocked_ when their jobs are rejected, they should be promoted to _trusted users_  when and they get a certain number of jobs approved.
