### ISSUE TITLE
Replace cookies with WebStorage (Local and Session)

### ISSUE THREAD

**Issue by ajpinedam** [developersdo/empleo-dot-net#482]

**Comment by Willjobs94** [comment]
What is the advantage of WebStorage over cookies? It would be nice if we can describe a little bit why the use is created. with all respect PinedaX

**Comment by eatskolnikov** [comment]
One advantage would be that unlike cookies, that would send the data stored to server with each server call, affecting the site’s performance, WebStorage works strictly on the client side.
