### ISSUE TITLE
Search is not working on CI

### ISSUE THREAD

**Issue by Willjobs94** [developersdo/empleo-dot-net#489]
I guess are the query string parameters that are not being set

**Comment by Willjobs94** [comment]
I found that it was a problem with some parameters not validating well on #469 @RaulMonteroC  let's check it out?

**Comment by RaulMonteroC** [comment]
@Willjobs94 I just saw your solution, it seems good. Haven't run the code yet but still is much easier to understand from what i previously wrote.
