### ISSUE TITLE
Sueldos de los puestos de trabajo

### ISSUE THREAD

**Issue by abatista667** [developersdo/empleo-dot-net#497]
Ya que los empleadores de RD estan negados a publicar cuanto son los salarios y debido a esto hay muchos Dev que perdemos el tiempo mandando nuestro CV a empresas y asistiendo a entrevistas para luego descartar un puesto debido a que la oferta salarial no es atractiva, propongo que sean los mismos Dev que tengan la habilidad de colocar el sueldo de las posiciones, este usuario tendrá esta información debido a que trabaja o ha trabajado recientemente en esa empresa.

Básicamente los Dev que han trabajado en una empresa dirán cuanto ganaban en la misma, el nombre del Dev deberia permanecer anónima.

**Comment by eatskolnikov** [comment]
Tengo mis reservas al respecto pero vamos a ver que dice la comunidad

**Comment by zxhadow** [comment]
Los rangos salariales son temas un tanto complejo. Pero https://www.glassdoor.com/ ofrece una buena solucion para llevar un estimado ademas de otras cosas.

**Comment by Willjobs94** [comment]
Para esto tendríamos que tener roles, para que un dev pueda iniciar sesión sin ser empresa.
