### ISSUE TITLE
No Soy Un Robot

### ISSUE THREAD

**Issue by CornelioWeb** [developersdo/empleo-dot-net#501]
Hey chicos, hoy he estado intentando publicar una oferta de empleo y todo bien menos la comprobación de "No soy un robot" que se queda cargando eternamente. Sea como sea, gran trabajo con el sitio web!

**Comment by eatskolnikov** [comment]
hmmm, intenta limpiar la caché del explorador (Ctrl + Shift + R) e intentando de nuevo

**Comment by CornelioWeb** [comment]
Intente eso y borrar todos los datos de navegación y nada

**Comment by eatskolnikov** [comment]
@CornelioWeb ¿Cómo te fue con este problema?
