### ISSUE TITLE
Error en filtro remoto

### ISSUE THREAD

**Issue by reneolivo** [developersdo/empleo-dot-net#508]
Cuando entro a la página, marco solamente "BUSCAR SOLO EMPLEOS REMOTOS", y le doy a "BUSCAR" la URL aparece así:

[http://emplea.do/jobs?IsRemote=true&IsRemote=false](http://emplea.do/jobs?IsRemote=true&IsRemote=false) (nota el `isRemote=true` y `isRemote=false` al mismo tiempo)

Aparte de ese error, otro caso extraño es que aparece un schrodinger job post a pesar de tener el remoto en verdadero/falso.....

**Comment by eatskolnikov** [comment]
@reneolivo Chequea esto

http://stackoverflow.com/questions/2697299/asp-net-mvc-why-is-html-checkbox-generating-an-additional-hidden-input

Cuando dejas un checkbox sin chequear el parámetro no se manda, por esto MVC genera un campo hidden, para que cuando hagas el submit se mapee el valor por defecto de la propiedad. En un GET request siempre se toma la primera ocurrencia del nombre del parámetro, así que cuando se mandan los dos el solamente toma el valor correcto.

Esa es la justificación, ahora, es cierto que no se ve estéticamente bien, voy a chequear esto eventualmente, después de 2.0

**Comment by reneolivo** [comment]
No es que se vea "estéticamente bien", es que ese filtro no funciona por ese error.....
