### ISSUE TITLE
En la lista de empleos solo muestra los últimos 7

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/empleo-dot-net#513]
Cuando haces clic en [Mostrar más empleos](http://emplea.do/jobsl) sólo muestra los últimos 7 empleos en lugar de todos 

![image](https://cloud.githubusercontent.com/assets/5460365/18413914/5fd4e3e4-7785-11e6-9a91-1e8b5e136cb4.png)

**Comment by DannyFeliz** [comment]
Alguien le podría meter mano este issue, considero que es algo urgente ya que actualmente emplea.do está funcionando como si solo se pueden ver 7 empleos y ya? @Willjobs94 @eatskolnikov

**Comment by chriscoderdr** [comment]
I think this is not happening anymore.

**Comment by DannyFeliz** [comment]
@cgomezmendez No pasa eso pero cuando le das a ver todas te salen un grupo de empleos random

**Comment by christianrd** [comment]
@DannyFeliz @eatskolnikov I think this issue should be closed.
