### ISSUE TITLE
No se puede crear una vacante en CI - problemas con recaptcha

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/empleo-dot-net#514]
![screen shot 2016-09-12 at 12 00 15 pm](https://cloud.githubusercontent.com/assets/5460365/18442902/89696f84-78e0-11e6-8574-b5a5136006d0.png)

**Comment by jugomez** [comment]
Esto fue corregido @eatskolnikov ?

**Comment by eatskolnikov** [comment]
@jugomez Me parece que sí
