### ISSUE TITLE
Nombre de cuenta invalido al realizar login con LinkedIn

### ISSUE THREAD

**Issue by YeralYamil** [developersdo/empleo-dot-net#515]
Cuando intento hacer login con LinkedIn me da este mensaje: "Enmanuel Toribio" would like to access some of your LinkedIn info:
![capture](https://cloud.githubusercontent.com/assets/3052715/18922160/9eb10e3c-8575-11e6-97e2-f44d295bf0b0.JPG)

**Comment by eatskolnikov** [comment]
This issue has been fixed, thanks for the report (: <3
![screen shot 2016-10-08 at 12 17 04 pm](https://cloud.githubusercontent.com/assets/1693000/19214417/3a04eb82-8d51-11e6-9bd8-91d5e08feb5f.png)
