### ISSUE TITLE
Segregar el IJobOpportunityService

### ISSUE THREAD

**Issue by jpozo20** [developersdo/empleo-dot-net#519]
Atendiendo a la "I" de Interface Segregation en SOLID, yo creo que este servicio se puede separar en varias interfaces y que el servicio las implemente todas. Aunque también se podría separar en diferentes servicios.

Por ejemplo, uno sería para el CRUD, otro sólo para traer los resultados y así.

**Comment by reneolivo** [comment]
Ejemplo, Pull Request, etc?

**Comment by jpozo20** [comment]
@reneolivo Nevermind, revisando mejor el código es el servicio del repositorio. Cuando lo abrí el issue pensé que hacía otras cosas además del CRUD. 

Cerraré el issue.
