### ISSUE TITLE
Compartir en redes sociales

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#52]
Agregar botón para compartir oferta en Twitter/Facebook/Demás

**Comment by jeanrodriguez** [comment]
nadie lo quizo, estare trabajando en ese desde ahora.
pd: no soy muy muy con eso de javascript asi que me dan una mano con cualquier cosa que vean mal jeje.

**Comment by amhed** [comment]
Dale, pa eso tamos :P 

BTW, hay varios servicios online como AddThis que sirven para agregar esto de forma fácil. Revisa eso a ver si vale la pena

**Comment by amhed** [comment]
http://www.addthis.com/
https://www.shareaholic.com/
http://www.sharethis.com/
https://www.addtoany.com/

Este me gusta:
http://simplesharingbuttons.com/

**Comment by amhed** [comment]
Closed by commit https://github.com/developersdo/empleo-dot-net/commit/f93fc68da04a29f7bc1a623c2f324515e3a7b33a
