### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by Amejia481** [developersdo/empleo-dot-net#523]
I have tried with every single login social provider that you have and I can't do log in without any error or explanation of what is happening.

**Comment by Eduardoveras** [comment]
This seems to be a very repetitive issue, they fix it every once in a while but it comes back, maybe it would be better to do a user-password login? and dont depende on external services to login

**Comment by rmariuzzo** [comment]
@Eduardoveras I think the user/password login should be added. If we are facing login issues from external providers then we should disable and depend to the user/password auth.

Meanwhile, we should investigate the root cause of this issue.
