### ISSUE TITLE
New Feature: Report a bug

### ISSUE THREAD

**Issue by Amejia481** [developersdo/empleo-dot-net#524]
It would be great if as an user I can report any issue that I having with the app, and it creates a Github issue for the developers of the project.

**P.S. Not all the user of the site are developers and they don't know how Github works**

**Comment by chriscoderdr** [comment]
I agree, usually people publish it in developersdo group in facebook but as you have said, not all the users of the service are developers, neither do all of them are in developersdo or have a facebook account.

**Comment by jeanrodriguez** [comment]
for basic functionality we can do something like this... maybe later we can add more stuff, like github has for create a new issue 

![new-bug](https://user-images.githubusercontent.com/5873551/36638349-c59f5a86-19c0-11e8-8a77-4c670b12b359.PNG)

**Comment by christianrd** [comment]
I agree with @jeanrodriguez, we can do something like this, getting email and name for response or whatever you want...

![image](https://user-images.githubusercontent.com/10536381/37245617-699136b8-2471-11e8-8624-27809955613a.png)
