### ISSUE TITLE
Ordenar los resultados de las búsquedas por categorías

### ISSUE THREAD

**Issue by jugomez** [developersdo/empleo-dot-net#526]
Cuando se selecciona una categoría el resultado no se ordenan por fecha de publicación de los empleos.
![screen shot 2017-08-04 at 12 15 33 am](https://user-images.githubusercontent.com/3052715/28954116-c6102ca0-78aa-11e7-88ed-3c1d1747d8bf.png)

Los empleos se deberían mostrar de forma descendente por su fecha de publicación.

**Comment by michaelmontero** [comment]
This is not happen anymore @jugomez .

**Comment by jpozo20** [comment]
As Michael said, this isn't happening anymore, so it can be closed. 
Cc: @eatskolnikov
