### ISSUE TITLE
Site Redesign

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/empleo-dot-net#527]
A redesign of the website's template

**Comment by jeanrodriguez** [comment]
if we use another template, maybe use a template with bootstrap 4

**Comment by eatskolnikov** [comment]
Possible android app client by @wilsonrc
![29027785_10215882097867940_3637133633745059840_o](https://user-images.githubusercontent.com/1693000/37485977-75923a84-2863-11e8-86a1-63503e5d2afc.png)
![29066826_10215882098307951_3273527307398021120_o](https://user-images.githubusercontent.com/1693000/37485978-75ac627e-2863-11e8-8c62-ec5073ea0048.png)
![29136766_10215882097707936_1266885528343543808_o](https://user-images.githubusercontent.com/1693000/37485979-75c33134-2863-11e8-8687-ce95a2b61487.png)

**Comment by eatskolnikov** [comment]
Website redesign proposal by Alfredo Martinez and Nahomi Sanchez
![website_proposal](https://user-images.githubusercontent.com/1693000/37486125-ea276572-2863-11e8-8060-2b8dbb28c248.png)
