### ISSUE TITLE
Migrate project to asp.net core

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#529]
Update the project to use the latest stable version of asp.net

**Comment by eatskolnikov** [comment]
I'm already working on this

**Comment by ajpinedam** [comment]
@eatskolnikov  still working on it?

**Comment by eatskolnikov** [comment]
@ajpinedam Yes, we are. We are going to tackle this one on two phases, first we will make a readonly API on .net core, then we will make the website project on .net core. Once @RaulMonteroC and I have something showable we will update here.
