### ISSUE TITLE
Mejoras al diseño

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#53]
Esté diseño me gustó: 
https://www.wfh.io/

**Comment by RaulMonteroC** [comment]
Ese diseño me gusto también. Si a los demás le gusto, me puedo encargar de implementarlo.

**Comment by jeanrodriguez** [comment]
creo que ese diseno esta bn jevy

**Comment by YhorbyMatias** [comment]
yo soporto esta bien chevere, sobrio y elegante.
