### ISSUE TITLE
Mostrar fecha de los empleos en vista mobile

### ISSUE THREAD

**Issue by jpozo20** [developersdo/empleo-dot-net#530]
Al visitar la página desde un dispositivo móvil, Galaxy S5 en mi caso, no se muestra la fecha de los empleos lo que no me permite saber si son actuales a menos que entre al empleo.

**Comment by jeanrodriguez** [comment]
check pull request  https://github.com/developersdo/empleo-dot-net/pull/533

**Comment by jeanrodriguez** [comment]
Close this one @claudiosanchez
