### ISSUE TITLE
Imagen de 404, no se ajusta en mobile, se ve cortada

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/empleo-dot-net#543]
![image](https://user-images.githubusercontent.com/1808624/39646123-6ef01e0a-4fa8-11e8-80eb-17652e2370e8.png)

**Comment by christianrd** [comment]
@raylinanthony  I'am working with this issue...

**Comment by christianrd** [comment]
@eatskolnikov  I think this issue must be closed.
