### ISSUE TITLE
Mejorar look and feel de "Más empleos de esta compañia"

### ISSUE THREAD

**Issue by raylinanthony** [developersdo/empleo-dot-net#545]
![image](https://user-images.githubusercontent.com/1808624/39646330-0bfae626-4fa9-11e8-8d49-944b62cfcda2.png)

**Comment by claudiosanchez** [comment]
¿Puedes elaborar más? Quizás explicar que se puede hacer para mejorar/hacer un mockup.

**Comment by eatskolnikov** [comment]
@raylinanthony ya tenemos un issue para el redisenño del sitio. Si tienes alguna sugerencia de diseño puedes agregarla ahí, el issue es #527

**Comment by raylinanthony** [comment]
Aquí mi idea.

![image](https://user-images.githubusercontent.com/1808624/39651894-a7e12f2c-4fb9-11e8-88bd-1272201a6e4b.png)
