### ISSUE TITLE
Los botones de share deben compartir el titulo

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#58]
Ahora mismo cuando compartes algo en twitter (solo he probado con twitter). Solo incluye el link, pero no el titulo de la oferta. Buscar una forma para mejorar esto

**Comment by jeanrodriguez** [comment]
ok. tranajando en eso :)

**Comment by jeanrodriguez** [comment]
@amhed resolvi lo del boton de compartir de twitter. pero veo el de google+ como q no funciona bn prueba a ver si te funciona.

tambien en el de compratir de facebook no se puede poner el titulo porque ese textbox es single line, no multiline como el de twitter o google+

**Comment by jeanrodriguez** [comment]
cuando puedas me confirma para ver si tengo que usar otra herramienta para eso de compartir

**Comment by amhed** [comment]
Si tu subes un pull request. Un exito

**Comment by jeanrodriguez** [comment]
jeje. @amhed como hago para poner todos los commit juntos. me dijiste que hiciera eso pero no le veo la vuelta. se que hay q usar rebase pero lo hago y na de na

**Comment by jeanrodriguez** [comment]
por eso no he hecho el pull request

**Comment by amhed** [comment]
Ve y haz el curso de git en code school. Tu branch está retrasado con respecto al branch principal. No has hecho pull del "upstream"

**Comment by amhed** [comment]
Perdon, mala mia, ya vi aqui: https://github.com/developersdo/empleo-dot-net/network. Que hiciste pull del upstream principal

**Comment by RaulMonteroC** [comment]
Este issue esta listo o falta algo más?

**Comment by amhed** [comment]
Creo que está ready. @jeanrodriguez confirma si se hizo merge (no recuerdo)

**Comment by jeanrodriguez** [comment]
Manana lo reviso y les dejo saber

**Comment by RaulMonteroC** [comment]
@jeanrodriguez Como va esto? Aún esta pendiente?

**Comment by RaulMonteroC** [comment]
Esto esta concluido.
