### ISSUE TITLE
Nombres semánticos para clases CSS

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#62]
Más info aquí: 
* http://css-tricks.com/semantic-class-names/
* http://stackoverflow.com/questions/6222731/should-css-class-names-like-floatleft-that-directly-describe-the-attached-styl

@RaulMonteroC

**Comment by RaulMonteroC** [comment]
Gracias, estaré trabajando en esto.

**Comment by RaulMonteroC** [comment]
Este issue debe ser cerrado porque ya se completo @amhed
