### ISSUE TITLE
Mejoras a la nueva tabla en página principal (/home/index)

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#63]
* En vez de tener la tabla de trabajos en la página principal, mover a un partial view
* En vez de retornar un modelo con los últimos 10 trabajos en HomeController, es mejor no retornar un modelo para el Index, y mover la logica del llenado a una accion en JobOpportunityController
* Actualizar /home/index.cshtml para que llame `@Html.Action` a JobOpportunityController y que renderice el partial con esa llamada

(quien coja esta avíseme para discutirlo)

**Comment by jeanrodriguez** [comment]
nadie dijo nada.  yo le entro

**Comment by FrancisTV** [comment]
somos dos

**Comment by jeanrodriguez** [comment]
@amhed creo que  este issues se puede cerrar.
