### ISSUE TITLE
Implementar LESS para definir los estilos de la página.

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#73]
Remplazar el código CSS existente por su contraparte en LESS para evitar duplicar las reglas y poder organizarlas mejor.

**Comment by FrancisTV** [comment]
estoy en eso

**Comment by RaulMonteroC** [comment]
Ese es mio.

**Comment by FrancisTV** [comment]
no relaje @RaulMonteroC bueno ok

**Comment by amhed** [comment]
:ghost: MuaaaaHahahahaha
