### ISSUE TITLE
Minificación automágica de LESS a CSS

### ISSUE THREAD

**Issue by amhed** [developersdo/empleo-dot-net#76]
http://www.asp.net/mvc/overview/performance/bundling-and-minification

**Comment by RaulMonteroC** [comment]
Una pregunta, trabajando con bootstrap me doy cuenta que el usa el modelo que yo utilizaba anteriormente (usando clases pequeñas que describen el comportamiento en vez de una que represente la funcionalidad lógica del elemento), en este caso, como se puede mantener semántico el HTML?

Se me ocurre incorporar esas pequeñas clases dentro de otras que la agrupen usando LESS para poder mantener la funcionalidad sin reescribir el css que ya tiene bootstrap y mantener semántico el HTML y más flexible a cambios.

¿Cómo lo haces tu?

**Comment by amhed** [comment]
No entendi :S (no soy el que más sabe CSS tampoco)

**Comment by RaulMonteroC** [comment]
Esta pregunta se cerrara porque hace mucho tiempo que no recibe atención.
