### ISSUE TITLE
Crear administración de usuarios

### ISSUE THREAD

**Issue by RaulMonteroC** [developersdo/empleo-dot-net#79]
Actualmente la aplicación no esta manejando perfiles de usuario. Sin embargo, es necesario crear perfiles de candidato y empresa, uno para la búsqueda de empleo y otro para la publicación.

Para la implementación de esta funcionalidad seria bueno aprovechar el framework de asp.net y utilizar entitity para lograr este objetivo.

**Comment by amhed** [comment]
Lo mejor es hacer esto con roles. 

ASP.NET tiene como 4 frameworks distintos para manejar los roles de usuarios y (para serte sincero) siempre me confundo/no se cual es cual. El último se llama identity, y parece que está muy bien hecho (pero no recuerdo si es MVC5 o MVC6)

Lo más lógico sería adicionar una tabla de roles para que un mismo usuario pueda publicar y aplicar. Digo, ahora que lo mencionas, para que un usuario quisiera loguearse? el punto del site es ser simple, y que sirva como clasificado solamente. Por que queremos identificar a quien está browseando?

**Comment by RaulMonteroC** [comment]
Aquí tenemos dos alternativas : 
* Podemos hacerlo simple como esta en el site de emplea.do actualmente donde no se inicia sesión, ni siquiera para publicar un empleo.

* Hacer algo complejo como tiene aldaba, donde se inicia sesión tanto para el candidato como para la empresa y esa información se usa para agrupar los trabajos de acuerdo a su perfil, facilitando la búsqueda (para el caso del candidato) y dar seguimiento a los trabajos que se han publicado (En el caso de la empresa)

Particularmente a mi me gusta la segunda opción porque la encuentro más completa e interesante siempre y cuando el candidato pueda ver toda la información de los empleos sin tener que iniciar sesión.

Como valor añadido, hacerlo de esta forma da la opción de poder probar los frameworks de manejo de usuario los cuales no se han tocado ninguno aún.

Podríamos dividir los tasks en diferentes issues de manera que sea un proceso evolutivo.

**Comment by amhed** [comment]
A mi me gusta la primera. No lo compliquemos. Despues hacemos una segunda version como aldaba

**Comment by amhed** [comment]
arreglemos lo de los roles. Cuando comencemos el proyecto de nuevo usando TDD entonces hacemos lo otro

**Comment by RaulMonteroC** [comment]
Estoy de acuerdo contigo. En ese caso movere esto para el backlog.

**Comment by sabdiel** [comment]
A mi me gustaria recibir notificaciones de nuevos trabajos que cumplan con mis criterios =) .. Si tu hace eso te doy mi email...=)

**Comment by sabdiel** [comment]
@RaulMonteroC  bro!!? Puedes cerrar la pregunta entonces? .. thanks

**Comment by amhed** [comment]
Señore yo creo @RaulMonteroC se murió o algo... no lo he vuelto a ver
