### ISSUE TITLE
Filtrar por categoria

### ISSUE THREAD

**Issue by gromney** [developersdo/empleo-dot-net#84]
Como un usuario me gustaria poder filtrar los empleos por categoria y asi me tomaria menos tiempo buscar las vacantes que me interesan.

Podria ser un dropdown como el diseño que le gusto a @amhed 

![filtrocategoria01](https://cloud.githubusercontent.com/assets/781571/7107923/adefc8d4-e143-11e4-86a6-5fcff3436280.png)

Pero yo prefiero que sea un tipo de listbox con multi select. :panda_face:

![filtrocategoria02](https://cloud.githubusercontent.com/assets/781571/7107938/1dd352ba-e144-11e4-8028-7973a92e12ae.png)

**Comment by amhed** [comment]
Yo no soy el main manager del proyecto ya. Tiene que surgir una persona nueva :frog:

**Comment by amhed** [comment]
Pensé que @RaulMonteroC se iba a hacer cargo de ahora en adelante, pero haceun par de semanas que no veo commits nuevos

**Comment by sabdiel** [comment]
Cool! Eso definitivamente provee valor.. also no han pensao en ponele paging al grid y hacer las columnas sortables? .. (that can help =) )

**Comment by jeanrodriguez** [comment]
hey si el paging ayudara mucho. me gusta mucho como esta el diseño de arriba de los job

**Comment by anyeloamt** [comment]
Está jevi este feature, ¿Puedo comenzar a desarrollarlo? 
Sería mi primera contribución en el proyecto.

**Comment by jeanrodriguez** [comment]
@anyeloamt  claro men que puedes.
Creao que puedes crear un issues y asignartelo y trabajar en eso.

**Comment by anyeloamt** [comment]
Jevi, le dí entonces.

**Comment by anyeloamt** [comment]
Por ahora está agregado como parte de los filtros en la cabeza de la página, también tiene un link en la categoría de cada row.
![screenshot](https://cloud.githubusercontent.com/assets/2273293/7217203/801a2cb0-e5e9-11e4-9ee4-88dc6e8bd50c.png)

No sé si hacer el PR así y luego hacer una sección de categorías en la parte izquierda de la página donde te diga la cantidad de vacantes disponible para cada una como el ejemplo de Working Nomads
![WorkingNomads](https://cloud.githubusercontent.com/assets/781571/7107938/1dd352ba-e144-11e4-8028-7973a92e12ae.png)

**Comment by sabdiel** [comment]
@anyeloamt de lo mio.. Cuando haras el PR?

**Comment by hminaya** [comment]
Esto ya se trabajo en el PR #152
