### ISSUE TITLE
Error al tratar de acceder a Nueva Vacante Page.

### ISSUE THREAD

**Issue by sabdiel** [developersdo/empleo-dot-net#85]
Este es el mensaje de bienvenida que aparece despues the clickear el boton the 'Nueva Vacante':

The associated metadata type for type 'EmpleoDotNet.ViewModel.NewJobOpportunityViewModel' contains the following unknown properties or fields: Tags. Please make sure that the names of these members match the names of the properties on the main type.

Note: el error es bn especifico, se alivia agregando that Tags array que menciona..  (Unit Tests No Found)

**Comment by gromney** [comment]
Imagino que cuando acepten el #78 ese error se soluciona

**Comment by sabdiel** [comment]
No se quien ni como.. pero esto ya no es un problema :) .. (Probably what you mentioned @gromney )
