### ISSUE TITLE
Introducir API para clientes moviles

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#90]

**Comment by YhorbyMatias** [comment]
Saludos Claudio me gustaria aprender  a trabajar en esa parte :)  , tu marca las pautas y / o documentación.

**Comment by eatskolnikov** [comment]
@YhorbyMatias el api va a ser un RESTful service, con .NET. La parte de que los clientes móviles la consuman es otro tema.

**Comment by AIsaac08** [comment]
Saludos, me gustaría aportar en esta parte, Entiendo que esta parte podría depender del refactoring donde se creará un library donde estarían los repositorios DTOs, etc. ¿Estoy en lo correcto?

**Comment by eatskolnikov** [comment]
@Alsaac08 estás en lo correcto

**Comment by anyeloamt** [comment]
Me imagino que ya se puede comenzar con esta parte, pronto lo necesitarán para el android app (que ya se está desarrollando).

**Comment by LuisAlbertoPenaNunez** [comment]
@anyeloamt ASAP

**Comment by jpozo20** [comment]
Estare haciendo un branch para trabajar en esta parte.

**Comment by jpozo20** [comment]
Agregué un proyecto web api con un controller que devuelve los jobs y permite hacer paging en el pull #520

**Comment by jpozo20** [comment]
Creo que con el merge #522 ya esto se puede cerrar @claudiosanchez @eatskolnikov. 
¿O faltaría agregar los filtros? Como location, nombre, etc.

**Comment by chriscoderdr** [comment]
Is it ready?
