### ISSUE TITLE
Postear Trabajos

### ISSUE THREAD

**Issue by claudiosanchez** [developersdo/empleo-dot-net#91]

**Comment by YhorbyMatias** [comment]
Me gustaria trabajar este issue

**Comment by luis-ramirez** [comment]
@YhorbyMatias estas trabajando en este task?

**Comment by YhorbyMatias** [comment]
nop , nadie me dio luz verde

**Comment by amhed** [comment]
? Loco como asi... Aquí uno dice "voy" y lo hace. No hay q esperar luz de
nadie

**Comment by luis-ramirez** [comment]
Jejeje, bueno, ya lo hice y haré un pull-request en breve, so, pregunté porque como tenía mucho que no sabía el estatus del project, pero como dice @ahmed no hay que preguntar y usted sólo dice le di a este issue y ya

**Comment by YhorbyMatias** [comment]
:( sorry soy nuevo en este asunto :p

**Comment by Ahmed** [comment]
jajaja

I don't understand anything from what you say.

**Comment by amhed** [comment]
LOL sorry @Ahmed someone made a typo :P
