### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#98]
Agregar tema bootstrap al proyecto

**Comment by luis-ramirez** [comment]
den sus opiniones a ver cual ponemos inicialmente de los temas que hay en esta pagina

http://bootswatch.com/

**Comment by claudiosanchez** [comment]
### Acceptance Criteria: 
* Seleccionar un Theme que sea compatible a nivel de features con los features de nuestro producto
* Introducir el Theme al Codebase
* Usar el Theme en los features ya hechos

**Comment by luis-ramirez** [comment]
He seleccionado este


http://coffeecreamthemes.com/themes/jobseek/site/

que opinan?

**Comment by eatskolnikov** [comment]
A mi me gusta

**Comment by luis-ramirez** [comment]
Cerraré este issue esto se resolvió en el PR #105
