### ISSUE TITLE
Agregar Identity

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/empleo-dot-net#99]
- Agregar Asp.NET Identity para manejar el login
- Solo podran crear trabajos los que esten logeados en la app
- Posibilidad de hacer login con FB, Microsoft y Google

**Comment by RaulMonteroC** [comment]
Usar ASP.Net identity para login y permitir el posteo esta pautada para la segunda etapa, según habiamos acordado en una reunión pasada.

El issue lo veo bien, lo colocare en etapa 2 y lo revisamos de nuevo una vez se termine la primera etapa.

**Comment by RaulMonteroC** [comment]
Me imagino que esto se refiere a crear login para usuarios tipo empresa con la posibilidad de postear trabajos. Es así @luis-ramirez ?

**Comment by luis-ramirez** [comment]
Si @RaulMonteroC

**Comment by RaulMonteroC** [comment]
Ok. Me encargare de esta parte entonces.
